// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityChangeInfoCardActivity } from "./ActivityChangeInfoCardActivity";
import type { ActivityChangeInfoCardStatusSlot } from "./ActivityChangeInfoCardStatusSlot";
import type { ActivityChangeInfoDrivingStatus } from "./ActivityChangeInfoDrivingStatus";
import type { ActivityChangeInfoSlot } from "./ActivityChangeInfoSlot";

/**
 * [ActivityChangeInfo: appendix 2.1.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e16027)
 */
export type ActivityChangeInfo = { slot: ActivityChangeInfoSlot, drivingStatus: ActivityChangeInfoDrivingStatus, slotStatus: ActivityChangeInfoCardStatusSlot, activity: ActivityChangeInfoCardActivity, minutes: number, };
