// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompanyCardApplicationIdentification } from "./CompanyCardApplicationIdentification";
import type { ControlCardApplicationIdentification } from "./ControlCardApplicationIdentification";
import type { DriverCardApplicationIdentification } from "./DriverCardApplicationIdentification";
import type { WorkshopCardApplicationIdentification } from "./WorkshopCardApplicationIdentification";

export type ApplicationIdentification = { "type": "DriverCard" } & DriverCardApplicationIdentification | { "type": "WorkshopCard" } & WorkshopCardApplicationIdentification | { "type": "ControlCard" } & ControlCardApplicationIdentification | { "type": "CompanyCard" } & CompanyCardApplicationIdentification;
