// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardApprovalNumber } from "./CardApprovalNumber";
import type { EmbedderIcAssemblerId } from "./EmbedderIcAssemblerId";
import type { ExtendedSerialNumberGen2 } from "./ExtendedSerialNumberGen2";
import type { ManufacturerCode } from "./ManufacturerCode";

/**
 * [CardIccIdentification: appendix 2.23.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17372)
 */
export type CardIccIdentificationGen2 = { clockStop: number, cardExtendedSerialNumber: ExtendedSerialNumberGen2, cardApprovalNumber: CardApprovalNumber, cardPersonaliserId: ManufacturerCode, embedderIcAssemblerId: EmbedderIcAssemblerId, icIdentifier: Array<number>, };
