// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaceRecordGen2 } from "./PlaceRecordGen2";

/**
 * [CardPlaceDailyWorkPeriod: appendix 2.27.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17729)
 */
export type CardPlaceDailyWorkPeriodGen2 = { placePointerNewestRecord: number, placeRecords: Array<PlaceRecordGen2>, };
