// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OdometerShort } from "./OdometerShort";
import type { TimeReal } from "./TimeReal";
import type { VehicleRegistrationIdentification } from "./VehicleRegistrationIdentification";
import type { VuDataBlockCounter } from "./VuDataBlockCounter";

/**
 * [CardVehicleRecord: appendix 2.37.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e18163)
 */
export type CardVehicleRecord = { vehicleOdometerBegin: OdometerShort, vehicleOdometerEnd: OdometerShort, vehicleFirstUse: TimeReal, vehicleLastUse: TimeReal, vehicleRegistration: VehicleRegistrationIdentification, vuDataBlockCounter: VuDataBlockCounter, };
