// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Name } from "./Name";
import type { NationNumeric } from "./NationNumeric";

/**
 * [CardDrivingLicenceInformation: appendix 2.18.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17139)
 */
export type CardDrivingLicenceInformation = { drivingLicenceIssuingAuthority: Name, drivingLicenceIssuingNation: NationNumeric, drivingLicenceNumber: string, };
