// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadType } from "./LoadType";
import type { TimeReal } from "./TimeReal";

/**
 * [CardLoadTypeEntryRecord: appendix 2.24b.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17521)
 */
export type CardLoadTypeEntryRecord = { timeStamp: TimeReal, loadTypeEntered: LoadType, };
