// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardVehicleRecordGen2 } from "./CardVehicleRecordGen2";

/**
 * [CardVehiclesUsed: appendix 2.38.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e18302)
 */
export type CardVehiclesUsedGen2 = { vehiclePointerNewestRecord: number, cardVehicleRecords: Array<CardVehicleRecordGen2>, };
