// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardActivityDailyRecord } from "./CardActivityDailyRecord";

/**
 * [CardDriverActivity: appendix 2.17.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17092)
 */
export type CardDriverActivity = { activityPointerOldestDayRecord: number, activityPointerNewestRecord: number, activityDailyRecords: Array<CardActivityDailyRecord>, };
