// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardEventRecordGen2 } from "./CardEventRecordGen2";

/**
 * [CardEventData: appendix 2.19.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17180)
 */
export type CardEventDataGen2 = { records: Array<Array<CardEventRecordGen2>>, };
