// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardVehicleUnitRecordGen2 } from "./CardVehicleUnitRecordGen2";

/**
 * [CardVehicleUnitsUsed: appendix 2.40.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e18350)
 */
export type CardVehicleUnitsUsedGen2 = { noOfCardVehicleUnitRecords: number, cardVehicleUnitRecords: Array<CardVehicleUnitRecordGen2>, };
