// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardFaultRecordGen2 } from "./CardFaultRecordGen2";

/**
 * [CardFaultData: appendix 2.22.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17340)
 */
export type CardFaultDataGen2 = { records: Array<Array<CardFaultRecordGen2>>, };
