// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardConsecutiveIndex } from "./CardConsecutiveIndex";
import type { CardRenewalIndex } from "./CardRenewalIndex";
import type { CardReplacementIndex } from "./CardReplacementIndex";
import type { IA5String } from "./IA5String";

/**
 * [CardNumber: appendix 2.26.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17629)
 */
export type CardNumber = { "type": "driver", driverIdentification: IA5String, cardReplacementIndex: CardReplacementIndex, cardRenewalIndex: CardRenewalIndex, } | { "type": "owner", ownerIdentification: IA5String, cardConsecutiveIndex: CardConsecutiveIndex, cardReplacementIndex: CardReplacementIndex, cardRenewalIndex: CardRenewalIndex, } | { "type": "none" };
