// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GNSSPlaceAuthRecord } from "./GNSSPlaceAuthRecord";
import type { NationNumeric } from "./NationNumeric";
import type { OdometerShort } from "./OdometerShort";

/**
 * [CardBorderCrossingRecord: appendix 2.11b.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e16857)
 */
export type CardBorderCrossingRecord = { 
/**
 * `countryLeft` is the country which was left by the vehicle, or `'no information available'` according to Annex IC requirement 147b.
 * `'Rest of the World'` (`NationNumeric` code `'FF'H`) shall be used when the vehicle unit is not able to determine the country where
 * the vehicle is located (e.g. the current country is not part of the stored digital maps).
 */
countryLeft: NationNumeric, 
/**
 * `countryEntered` is the country into which the vehicle has entered, or the country in which the vehicle is located at card insertion time.
 * `'Rest of the World'` (`NationNumeric` code `'FF'H`) shall be used when the vehicle unit is not able to determine the country where
 * the vehicle is located (e.g. the current country is not part of the stored digital maps).
 */
countryEntered: NationNumeric, gnssPlaceAuthRecord: GNSSPlaceAuthRecord, vehicleOdometerValue: OdometerShort, };
