// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardBorderCrossingRecord } from "./CardBorderCrossingRecord";

/**
 * [CardBorderCrossings: appendix 2.11a.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e16826)
 */
export type CardBorderCrossings = { borderCrossingPointerNewestRecord: number, cardBorderCrossingRecords: Array<CardBorderCrossingRecord>, };
