// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaceRecord } from "./PlaceRecord";

/**
 * [CardPlaceDailyWorkPeriod: appendix 2.27.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17729)
 */
export type CardPlaceDailyWorkPeriod = { placePointerNewestRecord: number, placeRecords: Array<PlaceRecord>, };
