// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventFaultType } from "./EventFaultType";
import type { TimeReal } from "./TimeReal";
import type { VehicleRegistrationIdentification } from "./VehicleRegistrationIdentification";

/**
 * [CardFaultData: appendix 2.21.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17292)
 */
export type CardFaultRecord = { faultType: EventFaultType, faultBeginTime: TimeReal, faultEndTime: TimeReal, faultVehicleRegistration: VehicleRegistrationIdentification, };
