// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardLoadTypeEntryRecord } from "./CardLoadTypeEntryRecord";

/**
 * [CardLoadTypeEntries: appendix 2.24a.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17490)
 */
export type CardLoadTypeEntries = { loadTypePointerNewestRecord: number, cardLoadTypeEntryRecords: Array<CardLoadTypeEntryRecord>, };
