// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardBorderCrossings } from "./CardBorderCrossings";
import type { CardLoadTypeEntries } from "./CardLoadTypeEntries";
import type { CardLoadUnloadOperations } from "./CardLoadUnloadOperations";
import type { CardPlacesAuthDailyWorkPeriod } from "./CardPlacesAuthDailyWorkPeriod";
import type { DriverCardApplicationIdentificationGen2V2 } from "./DriverCardApplicationIdentificationGen2V2";
import type { GNSSAuthAccumulatedDriving } from "./GNSSAuthAccumulatedDriving";
import type { SignatureGen2 } from "./SignatureGen2";
import type { VuConfigurations } from "./VuConfigurations";

export type CardGen2V2Blocks = { applicationIdentification: DriverCardApplicationIdentificationGen2V2, applicationIdentificationSignature: SignatureGen2, placesAuthentication: CardPlacesAuthDailyWorkPeriod, placesAuthenticationSignature: SignatureGen2, gnssPlacesAuthentication: GNSSAuthAccumulatedDriving, gnssPlacesAuthenticationSignature: SignatureGen2, borderCrossings: CardBorderCrossings, borderCrossingsSignature: SignatureGen2, loadUnloadOperations: CardLoadUnloadOperations, loadUnloadOperationsSignature: SignatureGen2, loadTypeEntries: CardLoadTypeEntries, loadTypeEntriesSignature: SignatureGen2, vuConfigurations: VuConfigurations | null, vuConfigurationsSignature: SignatureGen2 | null, };
