// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityChangeInfoCardActivity } from "./ActivityChangeInfoCardActivity";
import type { ActivityChangeInfoCardStatus } from "./ActivityChangeInfoCardStatus";
import type { ActivityChangeInfoSlot } from "./ActivityChangeInfoSlot";
import type { ActivityChangeInfoStatus } from "./ActivityChangeInfoStatus";

/**
 * [ActivityChangeInfo: appendix 2.1.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e16027)
 */
export type CardActivityChangeInfo = { slot: ActivityChangeInfoSlot, drivingOrFollowingActivityStatus: ActivityChangeInfoStatus, cardStatus: ActivityChangeInfoCardStatus, activity: ActivityChangeInfoCardActivity, minutes: number, };
