// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardChipIdentification } from "./CardChipIdentification";
import type { CardControlActivityDataRecordGen2 } from "./CardControlActivityDataRecordGen2";
import type { CardDownload } from "./CardDownload";
import type { CardDrivingLicenceInformation } from "./CardDrivingLicenceInformation";
import type { CardEventDataGen2 } from "./CardEventDataGen2";
import type { CardFaultDataGen2 } from "./CardFaultDataGen2";
import type { CardIccIdentificationGen2 } from "./CardIccIdentificationGen2";
import type { CardPlaceDailyWorkPeriodGen2 } from "./CardPlaceDailyWorkPeriodGen2";
import type { CardVehicleUnitsUsedGen2 } from "./CardVehicleUnitsUsedGen2";
import type { CardVehiclesUsedGen2 } from "./CardVehiclesUsedGen2";
import type { CertificateGen2 } from "./CertificateGen2";
import type { CurrentUsage } from "./CurrentUsage";
import type { DriverActivityData } from "./DriverActivityData";
import type { DriverCardApplicationIdentificationGen2 } from "./DriverCardApplicationIdentificationGen2";
import type { GnssAccumulatedDrivingGen2 } from "./GnssAccumulatedDrivingGen2";
import type { Identification } from "./Identification";
import type { SignatureGen2 } from "./SignatureGen2";
import type { SpecificConditionsGen2 } from "./SpecificConditionsGen2";

export type CardGen2Blocks = { cardIccIdentification: CardIccIdentificationGen2, cardChipIdentification: CardChipIdentification, applicationIdentification: DriverCardApplicationIdentificationGen2, applicationIdentificationSignature: SignatureGen2, cardSignCertificate: CertificateGen2, caCertificate: CertificateGen2, linkCertificate: CertificateGen2, identification: Identification, identificationSignature: SignatureGen2, cardDownload: CardDownload | null, cardDownloadSignature: SignatureGen2 | null, driverLicenceInfo: CardDrivingLicenceInformation | null, driverLicenceInfoSignature: SignatureGen2 | null, eventsData: CardEventDataGen2, eventsDataSignature: SignatureGen2, faultsData: CardFaultDataGen2, faultsDataSignature: SignatureGen2, driverActivityData: DriverActivityData, driverActivityDataSignature: SignatureGen2, vehiclesUsed: CardVehiclesUsedGen2, vehiclesUsedSignature: SignatureGen2, places: CardPlaceDailyWorkPeriodGen2, placesSignature: SignatureGen2, currentUsage: CurrentUsage | null, currentUsageSignature: SignatureGen2 | null, controlActivityData: CardControlActivityDataRecordGen2, controlActivityDataSignature: SignatureGen2, specificConditions: SpecificConditionsGen2, specificConditionsSignature: SignatureGen2, vehicleUnitsUsed: CardVehicleUnitsUsedGen2, vehicleUnitsUsedSignature: SignatureGen2, gnssAccumulatedDriving: GnssAccumulatedDrivingGen2, gnssPlacesSignature: SignatureGen2, };
