// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeReal } from "./TimeReal";
import type { VehicleRegistrationIdentification } from "./VehicleRegistrationIdentification";

/**
 * [CardCurrentUse appendix 2.16.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17059)
 */
export type CardCurrentUse = { sessionOpenTime: TimeReal, sessionOpenVehicle: VehicleRegistrationIdentification, };
