// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardLoadUnloadRecord } from "./CardLoadUnloadRecord";

/**
 * [CardLoadUnloadOperations: appendix 2.24c.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17544)
 */
export type CardLoadUnloadOperations = { loadUnloadPointerNewestRecord: number, cardLoadUnloadRecords: Array<CardLoadUnloadRecord>, };
