// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardIccIdentificationGen2 } from "./CardIccIdentificationGen2";

export type CardGen2V2Blocks = { cardIccIdentification: CardIccIdentificationGen2, };
