// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GNSSPlaceAuthRecord } from "./GNSSPlaceAuthRecord";
import type { OdometerShort } from "./OdometerShort";
import type { OperationType } from "./OperationType";
import type { TimeReal } from "./TimeReal";

/**
 * [CardLoadUnloadRecord: appendix 2.24d.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17576)
 */
export type CardLoadUnloadRecord = { timeStamp: TimeReal, operationType: OperationType, gnssPlaceAuthRecord: GNSSPlaceAuthRecord, vehicleOdometerValue: OdometerShort, };
