// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardSlotStatus } from "./CardSlotStatus";

/**
 * [CardSlotsStatus: appendix 2.34.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17939)
 */
export type CardSlotsStatus = { codriver: CardSlotStatus, driver: CardSlotStatus, };
