// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardBorderCrossings } from "./CardBorderCrossings";
import type { CardPlacesAuthDailyWorkPeriod } from "./CardPlacesAuthDailyWorkPeriod";
import type { DriverCardApplicationIdentificationGen2V2 } from "./DriverCardApplicationIdentificationGen2V2";
import type { GNSSAuthAccumulatedDriving } from "./GNSSAuthAccumulatedDriving";
import type { SignatureGen2 } from "./SignatureGen2";

export type CardGen2V2Blocks = { applicationIdentification: DriverCardApplicationIdentificationGen2V2, applicationIdentificationSignature: SignatureGen2, placesAuthentication: CardPlacesAuthDailyWorkPeriod, placesAuthenticationSignature: SignatureGen2, gnssPlacesAuthentication: GNSSAuthAccumulatedDriving, gnssPlacesAuthenticationSignature: SignatureGen2, borderCrossings: CardBorderCrossings, borderCrossingsSignature: SignatureGen2, };
