// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManufacturerCode } from "./ManufacturerCode";
import type { TimeReal } from "./TimeReal";
import type { VuSoftwareVersion } from "./VuSoftwareVersion";

/**
 * [CardVehicleUnitRecord: appendix 2.39.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e18302)
 */
export type CardVehicleUnitRecordGen2 = { timeStamp: TimeReal, manufacturerCode: ManufacturerCode, deviceId: number, vuSoftwareVersion: VuSoftwareVersion, };
