// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardStructureVersion } from "./CardStructureVersion";
import type { EquipmentType } from "./EquipmentType";

/**
 * [CompanyCardApplicationIdentification: appendix 2.48.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e18846)
 */
export type CompanyCardApplicationIdentification = { typeOfTachographCardId: EquipmentType, cardStructureVersion: CardStructureVersion, noOfCompanyRecords: number, };
