// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [ControlType: appendix 2.53.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e19148)
 */
export type ControlTypeGen2 = { cardDownloading: boolean, vuDownloading: boolean, printing: boolean, display: boolean, roadsideCalibrationChecking: boolean, };
