// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Datef } from "./Datef";
import type { HolderName } from "./HolderName";
import type { Language } from "./Language";

/**
 * [DriverCardHolderIdentification: appendix 2.62.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e19928)
 */
export type DriverCardHolderIdentification = { cardHolderNumber: HolderName, cardHolderBirthDate: Datef, cardHolderPreferredLanguage: Language, };
