// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [DriverCardApplicationIdentificationGen2V2: appendix 2.61a.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e19892)
 */
export type DriverCardApplicationIdentificationGen2V2 = { lengthOfFollowingData: number, noOfBorderCrossingRecords: number, noOfLoadUnloadRecords: number, noOfLoadTypeEntryRecords: number, vuConfigurationLengthRange: number, };
