// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardDriverActivity } from "./CardDriverActivity";

/**
 * EF Block page 281
 */
export type DriverActivityData = { cardDriverActivity: CardDriverActivity, };
