// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IA5String } from "./IA5String";

/**
 * [EmbedderIcAssemblerId: appendix 2.65.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e20005)
 */
export type EmbedderIcAssemblerId = { countryCode: IA5String, moduleEmbedder: number, manufacturerInformation: number, };
