// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [EntryTypeDailyWorkPeriod: appendix 2.66.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e20044)
 */
export type EntryTypeDailyWorkPeriodGen2 = "BeginRelatedTimeCardInsertionTimeOrTimeOfEntry" | "EndRelatedTimeCardWithdrawalTimeOrTimeOfEntry" | "BeginRelatedTimeManuallyEntered" | "EndRelatedTimeManuallyEntered";
