// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EquipmentTypeGen2 = "Reserved" | "DriverCard" | "WorkshopCard" | "ControlCard" | "CompanyCard" | "ManufacturingCard" | "VehicleUnit" | "MotionSensor" | "GNSSFacility" | "RemoteCommunicationDevice" | "ITSinterfaceModule" | "Plaque" | "M1N1Adapter" | "CAERCA" | "CAMSCA" | "ExternalGNSSConnection" | "Unused" | "DriverCardSign" | "WorkshopCardSign" | "VehicleUnitSign" | "RFU";
