// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [EquipmentType: appendix 2.67.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e20100)
 */
export type EquipmentType = "Reserved" | "DriverCard" | "WorkshopCard" | "ControlCard" | "CompanyCard" | "ManufacturingCard" | "VehicleUnit" | "MotionSensor" | "RFU";
