// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [EventFaultRecordPurpose: appendix 2.69.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e20262)
 */
export type EventFaultRecordPurpose = "OneOfTenMostRecentOrLast" | "LongestEventLastTenDays" | "OneOfFiveLongestEventsLastYear" | "LastEventLastTenDays" | "MostSeriousEventLastTenDays" | "OneOfFiveMostSeriousEventsLastYear" | "FirstEventAfterLastCalibration" | "ActiveOrOngoing" | "RFU" | "ManufacturerSpecific";
