// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IA5String } from "./IA5String";
import type { SealManufacturerCode } from "./SealManufacturerCode";

/**
 * [ExtendedSealIdentifier: appendix 2.71.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e21276)
 */
export type ExtendedSealIdentifierGen2 = { manufacturerCode: SealManufacturerCode | null, sealIdentifier: IA5String | null, };
