// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManufacturerCode } from "./ManufacturerCode";
import type { MonthYear } from "./MonthYear";

/**
 * [ExtendedSerialNumber: appendix 2.72.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e21307)
 */
export type ExtendedSerialNumber = { serialNumber: number, monthYear: MonthYear, type: number, manufacturerCode: ManufacturerCode, };
