// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FullCardNumberGen2 } from "./FullCardNumberGen2";
import type { GenerationGen2 } from "./GenerationGen2";

/**
 * [FullCardNumberAndGeneration: appendix 2.74.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e21438)
 */
export type FullCardNumberAndGenerationGen2 = { fullCardNumber: FullCardNumberGen2, generation: GenerationGen2, };
