// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeoCoordinatesGen2 } from "./GeoCoordinatesGen2";
import type { GnssAccuracyGen2 } from "./GnssAccuracyGen2";
import type { PositionAuthenticationStatus } from "./PositionAuthenticationStatus";
import type { TimeReal } from "./TimeReal";

/**
 * [GNSSPlaceAuthRecord: appendix 2.79c.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e21739)
 */
export type GNSSPlaceAuthRecord = { timeStamp: TimeReal, gnssAccuracy: GnssAccuracyGen2, gnssCoordinates: GeoCoordinatesGen2, authenticationStatus: PositionAuthenticationStatus, };
