// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PositionAuthenticationStatus } from "./PositionAuthenticationStatus";
import type { TimeReal } from "./TimeReal";

/**
 * [GNSSAuthStatusADRecord: appendix 2.79a.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e21683)
 */
export type GNSSAuthStatusADRecord = { timeStamp: TimeReal, authenticationStatus: PositionAuthenticationStatus, };
