// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GNSSAccumulatedDrivingRecordGen2 } from "./GNSSAccumulatedDrivingRecordGen2";

/**
 * [GNSSAccumulatedDriving: appendix 2.79.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e21595)
 */
export type GnssAccumulatedDrivingGen2 = { gnssAdPointerNewestRecord: number, gnssAccumulatedDrivingRecords: Array<GNSSAccumulatedDrivingRecordGen2>, };
