// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardIdentification } from "./CardIdentification";
import type { DriverCardHolderIdentification } from "./DriverCardHolderIdentification";

/**
 * [Identification: appendix 4.2.2.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e41651)
 */
export type Identification = { cardIdentification: CardIdentification, driverCardHolderIdentification: DriverCardHolderIdentification, };
