// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [LoadType: appendix 2.90a.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e22110)
 */
export type LoadType = "UndefinedLoadType" | "Goods" | "Passengers" | "RFU";
