// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManufacturerCode } from "./ManufacturerCode";

/**
 * [ManufacturerSpecificEventFaultData: appendix 2.95.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e22276)
 */
export type ManufacturerSpecificEventFaultDataGen2 = { manufacturerCode: ManufacturerCode, manufacturerSpecificErrorCode: Array<number>, };
