// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardData } from "./CardData";
import type { TachoFileType } from "./TachoFileType";
import type { VuData } from "./VuData";

export type NoopStruct = { card_data: CardData, vu_data: VuData, tacho_file_type: TachoFileType, };
