// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [OperationType: appendix 2.114a.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e22905)
 */
export type OperationType = "RFU" | "LoadOperation" | "UnloadOperation" | "SimultaneousLoadUnloadOperation";
