// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PositionAuthenticationStatus } from "./PositionAuthenticationStatus";
import type { TimeReal } from "./TimeReal";

/**
 * [PlaceAuthStatusRecord: appendix 2.116b.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e23087)
 */
export type PlaceAuthStatusRecord = { entryTime: TimeReal, authenticationStatus: PositionAuthenticationStatus, };
