// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryTypeDailyWorkPeriodGen2 } from "./EntryTypeDailyWorkPeriodGen2";
import type { GNSSPlaceAuthRecord } from "./GNSSPlaceAuthRecord";
import type { NationNumeric } from "./NationNumeric";
import type { OdometerShort } from "./OdometerShort";
import type { RegionNumeric } from "./RegionNumeric";
import type { TimeReal } from "./TimeReal";

/**
 * [PlaceAuthRecord: appendix 2.216a.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e23047)
 */
export type PlaceAuthRecord = { entryTime: TimeReal, entryTypeDailyWorkPeriod: EntryTypeDailyWorkPeriodGen2, dailyWorkPeriodCountry: NationNumeric, dailyWorkPeriodRegion: RegionNumeric, vehicleOdometerValue: OdometerShort, entryGnssPlaceAuthRecord: GNSSPlaceAuthRecord, };
