// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryTypeDailyWorkPeriod } from "./EntryTypeDailyWorkPeriod";
import type { NationNumeric } from "./NationNumeric";
import type { OdometerShort } from "./OdometerShort";
import type { RegionNumeric } from "./RegionNumeric";
import type { TimeReal } from "./TimeReal";

/**
 * [PlaceRecord: appendix 2.117.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e23112)
 */
export type PlaceRecord = { entryTime: TimeReal, entryTypeDailyWorkPeriod: EntryTypeDailyWorkPeriod, dailyWorkPeriodCountry: NationNumeric, dailyWorkPeriodRegion: RegionNumeric, vehicleOdometerValue: OdometerShort, };
