// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [PositionAuthenticationStatus: appendix 2.117a.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e23200)
 */
export type PositionAuthenticationStatus = "NotAuthenticated" | "Authenticated" | "RFU";
