// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SealRecordGen2 } from "./SealRecordGen2";

/**
 * [SealDataVu: appendix 2.129.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e23827)
 */
export type SealDataVuGen2 = { sealRecords: Array<SealRecordGen2>, };
