// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EquipmentTypeGen2 } from "./EquipmentTypeGen2";
import type { ExtendedSealIdentifierGen2 } from "./ExtendedSealIdentifierGen2";

/**
 * [SealRecord: appendix 2.130.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e23854)
 */
export type SealRecordGen2 = { equipmentType: EquipmentTypeGen2, extendedSealIdentifier: ExtendedSealIdentifierGen2, };
