// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * https://dtc.jrc.ec.europa.eu/dtc_seal_manufacturer_code.php.html
 */
export type SealManufacturerCode = string;
