// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtendedSerialNumber } from "./ExtendedSerialNumber";
import type { SensorApprovalNumber } from "./SensorApprovalNumber";
import type { TimeReal } from "./TimeReal";

/**
 * [SensorPaired: appendix 2.144.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24360)
 */
export type SensorPaired = { sensorSerialNumber: ExtendedSerialNumber, sensorApprovalNumber: SensorApprovalNumber, sensorPairingDateFirst: TimeReal, };
