// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtendedSerialNumberGen2 } from "./ExtendedSerialNumberGen2";
import type { SensorExternalGnssApprovalNumberGen2 } from "./SensorExternalGnssApprovalNumberGen2";
import type { TimeReal } from "./TimeReal";

export type SensorExternalGNSSCoupledRecordGen2 = { sensorSerialNumber: ExtendedSerialNumberGen2, sensorApprovalNumber: SensorExternalGnssApprovalNumberGen2, sensorCouplingDate: TimeReal, };
