// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtendedSerialNumberGen2 } from "./ExtendedSerialNumberGen2";
import type { SensorApprovalNumberGen2 } from "./SensorApprovalNumberGen2";
import type { TimeReal } from "./TimeReal";

export type SensorPairedRecordGen2 = { sensorSerialNumber: ExtendedSerialNumberGen2, sensorApprovalNumber: SensorApprovalNumberGen2, sensorPairingDate: TimeReal, };
