// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [SpecificConditionType: appendix 2.154.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24685)
 */
export type SpecificConditionType = "RFU" | "OutOfScopeBegin" | "OutOfScopeEnd" | "FerryTrainCrossingBegin";
