// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecificConditionType } from "./SpecificConditionType";
import type { TimeReal } from "./TimeReal";

/**
 * [SpecificConditionRecord: appendix 2.152.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24614)
 */
export type SpecificConditionRecord = { entryTime: TimeReal, specificConditionType: SpecificConditionType, };
