// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecificConditionRecordGen2 } from "./SpecificConditionRecordGen2";

/**
 * [SpecificConditions: appendix 2.153.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24644)
 */
export type SpecificConditionsGen2 = { conditionPointerNewestRecord: number, specificConditionRecords: Array<SpecificConditionRecordGen2>, };
