// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TachoFileType = "VehicleUnitGen1" | "VehicleUnitGen2" | "VehicleUnitGen2V2" | "DriverCardGen1" | "DriverCardGen2" | "DriverCardGen2V2";
