// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NationNumeric } from "./NationNumeric";
import type { VehicleRegistrationNumber } from "./VehicleRegistrationNumber";

/**
 * [VehicleRegistrationIdentification: appendix 2.116.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e25120)
 */
export type VehicleRegistrationIdentification = { vehicleRegistrationNation: NationNumeric, vehicleRegistrationNumber: VehicleRegistrationNumber, };
