// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityChangeInfo } from "./ActivityChangeInfo";

/**
 * [VuActivityDailyData: appendix 2.170.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e25344)
 */
export type VuActivityDailyData = { noOfActivityChanges: number, activityChangeInfos: Array<ActivityChangeInfo>, };
