// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardActivityChangeInfo } from "./CardActivityChangeInfo";
import type { DateOfDayDownloadedGen2 } from "./DateOfDayDownloadedGen2";
import type { OdometerShort } from "./OdometerShort";
import type { SignatureGen2 } from "./SignatureGen2";
import type { SpecificConditionRecordGen2 } from "./SpecificConditionRecordGen2";
import type { VuCardIwRecordGen2 } from "./VuCardIwRecordGen2";
import type { VuGNSSADRecordGen2 } from "./VuGNSSADRecordGen2";
import type { VuPlaceDailyWorkPeriodRecordGen2 } from "./VuPlaceDailyWorkPeriodRecordGen2";

export type VuActivitiesBlockGen2 = { dateOfDayDownloadedRecordArray: Array<DateOfDayDownloadedGen2>, odometerValueMidnightRecordArray: Array<OdometerShort>, vuCardIwRecordArray: Array<VuCardIwRecordGen2>, vuActivityDailyRecordArray: Array<CardActivityChangeInfo>, vuPlaceDailyWorkPeriodRecordArray: Array<VuPlaceDailyWorkPeriodRecordGen2>, vuGnssAdRecordArray: Array<VuGNSSADRecordGen2>, vuSpecificConditionRecordArray: Array<SpecificConditionRecordGen2>, signatureRecordArray: Array<SignatureGen2>, };
