// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OdometerShort } from "./OdometerShort";
import type { Signature } from "./Signature";
import type { TimeReal } from "./TimeReal";
import type { VuActivityDailyData } from "./VuActivityDailyData";
import type { VuCardIWData } from "./VuCardIWData";
import type { VuPlaceDailyWorkPeriodData } from "./VuPlaceDailyWorkPeriodData";
import type { VuSpecificConditionData } from "./VuSpecificConditionData";

/**
 * Page 344 TREP 02
 */
export type VuActivitiesBlock = { timeReal: TimeReal, odometerValueMidnight: OdometerShort, vuCardIwData: VuCardIWData, vuActivityDailyData: VuActivityDailyData, vuPlaceDailyWorkPeriodData: VuPlaceDailyWorkPeriodData, vuSpecificConditionData: VuSpecificConditionData, signature: Signature, };
