// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FullCardNumberAndGenerationGen2 } from "./FullCardNumberAndGenerationGen2";
import type { GNSSPlaceAuthRecord } from "./GNSSPlaceAuthRecord";
import type { NationNumeric } from "./NationNumeric";
import type { OdometerShort } from "./OdometerShort";

/**
 * [VuBorderCrossingRecord: appendix 2.203a.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e27413)
 */
export type VuBorderCrossingRecord = { cardNumberAndGenDriverSlot: FullCardNumberAndGenerationGen2 | null, cardNumberAndGenCodriverSlot: FullCardNumberAndGenerationGen2 | null, countryLeft: NationNumeric, countryEntered: NationNumeric, gnssPlaceAuthRecord: GNSSPlaceAuthRecord, vehicleOdometerValue: OdometerShort, };
