// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardNumber } from "./CardNumber";
import type { CardStructureVersion } from "./CardStructureVersion";
import type { ExtendedSerialNumberGen2 } from "./ExtendedSerialNumberGen2";
import type { FullCardNumberAndGenerationGen2 } from "./FullCardNumberAndGenerationGen2";

export type VuCardRecordGen2 = { cardNumberAndGenerationInformation: FullCardNumberAndGenerationGen2 | null, cardExtendedSerialNumber: ExtendedSerialNumberGen2, cardStructureVersion: CardStructureVersion, cardNumber: CardNumber | null, };
