// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardSlotNumber } from "./CardSlotNumber";
import type { FullCardNumber } from "./FullCardNumber";
import type { HolderName } from "./HolderName";
import type { ManualInputFlag } from "./ManualInputFlag";
import type { OdometerShort } from "./OdometerShort";
import type { PreviousVehicleInfo } from "./PreviousVehicleInfo";
import type { TimeReal } from "./TimeReal";

/**
 * [VuCardIwRecord: appendix 2.177.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e25809)
 */
export type VuCardIwRecord = { cardHolderName: HolderName, fullCardNumber: FullCardNumber, cardExpiryDate: TimeReal, cardInsertionTime: TimeReal, vehicleOdometerValueAtInsertion: OdometerShort, cardSlotNumber: CardSlotNumber, cardWithdrawalTime: TimeReal | null, vehicleOdometerValueAtWithdrawal: OdometerShort, previousVehicleInfo: PreviousVehicleInfo | null, manualEntryFlag: ManualInputFlag | null, };
