// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VuCalibrationRecord } from "./VuCalibrationRecord";

/**
 * [VuCalibrationData: appendix 2.173.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e25471)
 */
export type VuCalibrationData = { noOfVuCalibrationRecords: number, vuCalibrationRecords: Array<VuCalibrationRecord>, };
