// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VuCardIwRecord } from "./VuCardIwRecord";

export type VuCardIWData = { noOfIwRecords: number, vuCardIwRecords: Array<VuCardIwRecord>, };
