// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardSlotNumber } from "./CardSlotNumber";
import type { FullCardNumberAndGenerationGen2 } from "./FullCardNumberAndGenerationGen2";
import type { HolderName } from "./HolderName";
import type { ManualInputFlag } from "./ManualInputFlag";
import type { OdometerShort } from "./OdometerShort";
import type { PreviousVehicleInfoGen2 } from "./PreviousVehicleInfoGen2";
import type { TimeReal } from "./TimeReal";

export type VuCardIwRecordGen2 = { cardHolderName: HolderName, fullCardNumberAndGeneration: FullCardNumberAndGenerationGen2, cardExpiryDate: TimeReal, cardInsertionDate: TimeReal, vehicleOdometerValueAtInsertion: OdometerShort, cardSlotNumber: CardSlotNumber, cardWithdrawlTime: TimeReal | null, vehicleOdometerValueAtWithdrawal: OdometerShort, previousVehicleInfo: PreviousVehicleInfoGen2, manualInputFlag: ManualInputFlag, };
