// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SensorExternalGNSSCoupledRecordGen2 } from "./SensorExternalGNSSCoupledRecordGen2";
import type { SensorPairedRecordGen2 } from "./SensorPairedRecordGen2";
import type { SignatureGen2 } from "./SignatureGen2";
import type { VuCalibrationRecordGen2V2 } from "./VuCalibrationRecordGen2V2";
import type { VuCardRecordGen2 } from "./VuCardRecordGen2";
import type { VuITSConsentRecordGen2 } from "./VuITSConsentRecordGen2";
import type { VuIdentificationGen2V2 } from "./VuIdentificationGen2V2";
import type { VuPowerSupplyInterruptionRecordGen2V2 } from "./VuPowerSupplyInterruptionRecordGen2V2";

/**
 * TREP 0x35 page 349
 */
export type VuCompanyLocksGen2V2 = { 
/**
 * All VU identification data stored in the VU
 */
vuIdentificationRecordArray: Array<VuIdentificationGen2V2>, 
/**
 * All MS pairings stored in the VU
 */
vuSensorPairedRecordArray: Array<SensorPairedRecordGen2>, 
/**
 * All external GNSS facility couplings stored in the VU
 */
vuSensorExternalGnssCoupledRecordArray: Array<SensorExternalGNSSCoupledRecordGen2>, 
/**
 * All calibration records stored in the VU
 */
vuCalibrationRecordArray: Array<VuCalibrationRecordGen2V2>, 
/**
 * All card insertion data stored in the VU
 */
vuCardRecordArray: Array<VuCardRecordGen2>, 
/**
 * All ITS consent records stored in the VU
 */
vuItsConsentRecordArray: Array<VuITSConsentRecordGen2>, 
/**
 * All power supply interruption records stored in the VU
 */
vuPowerSupplyInterruptionRecordArray: Array<VuPowerSupplyInterruptionRecordGen2V2>, signatureRecordArray: Array<SignatureGen2>, };
