// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VuCompanyLocksRecord } from "./VuCompanyLocksRecord";

/**
 * [VuCompanyLocksData: appendix 2.183.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e26258)
 */
export type VuCompanyLocksData = { noOfLocks: number, vuCompanyLocksRecords: Array<VuCompanyLocksRecord>, };
