// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VuControlActivityRecord } from "./VuControlActivityRecord";

/**
 * [VuControlActivityData: appendix 2.186.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e26342)
 */
export type VuControlActivityData = { noOfControls: number, vuControlActivityRecords: Array<VuControlActivityRecord>, };
