// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlTypeGen2 } from "./ControlTypeGen2";
import type { FullCardNumberAndGenerationGen2 } from "./FullCardNumberAndGenerationGen2";
import type { TimeReal } from "./TimeReal";

export type VuControlActivityGen2 = { controlType: ControlTypeGen2, controlTime: TimeReal, controlCardNumberAndGeneration: FullCardNumberAndGenerationGen2, downloadPeriodBeginTime: TimeReal, downloadPeriodEndTime: TimeReal, };
