// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * VuConfigurations: there is no documentation for this block in the spec, none at all, so we'll just process the bytes
 */
export type VuConfigurations = Array<number>;
