// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlTypeGen2 } from "./ControlTypeGen2";
import type { FullCardNumberAndGenerationGen2 } from "./FullCardNumberAndGenerationGen2";
import type { TimeReal } from "./TimeReal";

/**
 * [VuControlActivityRecord: appendix 2.187.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e26376)
 */
export type VuControlActivityRecordGen2 = { controlType: ControlTypeGen2, controlTime: TimeReal, controlCardNumberAndGeneration: FullCardNumberAndGenerationGen2, downloadPeriodBeginTime: TimeReal, downloadPeriodEndTime: TimeReal, };
