// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VuGen1Blocks } from "./VuGen1Blocks";
import type { VuGen2Blocks } from "./VuGen2Blocks";
import type { VuGen2V2Blocks } from "./VuGen2V2Blocks";

export type VuData = { "generation": "gen1" } & VuGen1Blocks | { "generation": "gen2" } & VuGen2Blocks | { "generation": "gen2V2" } & VuGen2V2Blocks;
