// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Signature } from "./Signature";
import type { VuDetailedSpeedData } from "./VuDetailedSpeedData";

export type VuDetailedSpeedBlock = { vuDetailedSpeedData: VuDetailedSpeedData, signature: Signature, };
