// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VuDetailedSpeedBlock } from "./VuDetailedSpeedBlock";

/**
 * [VuDetailedSpeedData: appendix 2.192.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e26618)
 */
export type VuDetailedSpeedData = { noOfSpeedBlocks: number, vuDetailedSpeedRecords: Array<VuDetailedSpeedBlock>, };
