// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FullCardNumberAndGenerationGen2 } from "./FullCardNumberAndGenerationGen2";
import type { Name } from "./Name";
import type { TimeReal } from "./TimeReal";

export type VuDownloadActivityDataGen2 = { downloadingTime: TimeReal | null, fullCardNumberAndGeneration: FullCardNumberAndGenerationGen2 | null, companyOrWorkshopName: Name | null, };
