// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignatureGen2 } from "./SignatureGen2";
import type { VuEventRecordGen2 } from "./VuEventRecordGen2";
import type { VuFaultRecordGen2 } from "./VuFaultRecordGen2";
import type { VuOverSpeedingControlDataGen2 } from "./VuOverSpeedingControlDataGen2";
import type { VuOverSpeedingEventRecordGen2 } from "./VuOverSpeedingEventRecordGen2";
import type { VuTimeAdjustmentRecordGen2 } from "./VuTimeAdjustmentRecordGen2";

export type VuEventsAndFaultsBlockGen2 = { vuFaultRecordArray: Array<VuFaultRecordGen2>, vuEventRecordArray: Array<VuEventRecordGen2>, vuOverSpeedingControlDataRecordArray: Array<VuOverSpeedingControlDataGen2>, vuOverSpeedingEventRecordArray: Array<VuOverSpeedingEventRecordGen2>, vuTimeAdjustmentRecordArray: Array<VuTimeAdjustmentRecordGen2>, signatureRecordArray: Array<SignatureGen2>, };
