// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Signature } from "./Signature";
import type { VuEventData } from "./VuEventData";
import type { VuFaultData } from "./VuFaultData";
import type { VuOverSpeedingControlData } from "./VuOverSpeedingControlData";
import type { VuOverSpeedingEventData } from "./VuOverSpeedingEventData";
import type { VuTimeAdjustmentData } from "./VuTimeAdjustmentData";

/**
 * TREP 03 page 346
 */
export type VuEventsAndFaultsBlock = { vuFaultData: VuFaultData, vuEventData: VuEventData, vuOverSpeedingControlData: VuOverSpeedingControlData, vuOverSpeedingEventData: VuOverSpeedingEventData, vuTimeAdjustmentData: VuTimeAdjustmentData, signature: Signature, };
