// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventFaultRecordPurpose } from "./EventFaultRecordPurpose";
import type { EventFaultType } from "./EventFaultType";
import type { FullCardNumber } from "./FullCardNumber";
import type { SimilarEventsNumber } from "./SimilarEventsNumber";
import type { TimeReal } from "./TimeReal";

/**
 * [VuEventRecord: appendix 2.197.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e26910)
 */
export type VuEventRecord = { eventType: EventFaultType, eventRecordPurpose: EventFaultRecordPurpose, eventBeginTime: TimeReal, eventEndTime: TimeReal | null, cardNumberDriverSlotBegin: FullCardNumber | null, cardNumberCodriverSlotBegin: FullCardNumber | null, cardNumberDriverSlotEnd: FullCardNumber | null, cardNumberCodriverSlotEnd: FullCardNumber | null, similarEventsNumber: SimilarEventsNumber, };
