// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VuFaultRecord } from "./VuFaultRecord";

/**
 * [VuFaultRecord: appendix 2.200.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e27122)
 */
export type VuFaultData = { noOfVuFaultRecords: number, vuFaultRecords: Array<VuFaultRecord>, };
