// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventFaultRecordPurpose } from "./EventFaultRecordPurpose";
import type { EventFaultType } from "./EventFaultType";
import type { FullCardNumber } from "./FullCardNumber";
import type { TimeReal } from "./TimeReal";

/**
 * [VuFaultRecord: appendix 2.201.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e27156)
 */
export type VuFaultRecord = { faultType: EventFaultType, faultRecordPurpose: EventFaultRecordPurpose, faultBeginTime: TimeReal, faultEndTime: TimeReal, cardNumberDriverSlotBegin: FullCardNumber | null, cardNumberCodriverSlotBegin: FullCardNumber | null, cardNumberDriverSlotEnd: FullCardNumber | null, cardNumberCodriverSlotEnd: FullCardNumber | null, };
