// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VuOverviewBlock } from "./VuOverviewBlock";

export type VuGen2V2Blocks = { vuOverview: VuOverviewBlock, };
