// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VuActivitiesBlock } from "./VuActivitiesBlock";
import type { VuCompanyLocksBlock } from "./VuCompanyLocksBlock";
import type { VuDetailedSpeedData } from "./VuDetailedSpeedData";
import type { VuEventsAndFaultsBlock } from "./VuEventsAndFaultsBlock";
import type { VuOverviewBlock } from "./VuOverviewBlock";

export type VuGen1Blocks = { vuOverview: VuOverviewBlock, vuActivities: Array<VuActivitiesBlock>, vuEventsAndFaults: Array<VuEventsAndFaultsBlock>, vuDetailedSpeed: Array<VuDetailedSpeedData>, vuCompanyLocks: Array<VuCompanyLocksBlock>, };
