// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VuActivitiesBlockGen2 } from "./VuActivitiesBlockGen2";
import type { VuCompanyLocksGen2 } from "./VuCompanyLocksGen2";
import type { VuDetailedSpeedBlockGen2 } from "./VuDetailedSpeedBlockGen2";
import type { VuEventsAndFaultsBlockGen2 } from "./VuEventsAndFaultsBlockGen2";
import type { VuOverviewBlockGen2 } from "./VuOverviewBlockGen2";

export type VuGen2Blocks = { vuOverview: VuOverviewBlockGen2, vuActivities: Array<VuActivitiesBlockGen2>, vuEventsAndFaults: Array<VuEventsAndFaultsBlockGen2>, vuDetailedSpeed: Array<VuDetailedSpeedBlockGen2>, vuCompanyLocks: Array<VuCompanyLocksGen2>, };
