// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VuActivitiesBlockGen2V2 } from "./VuActivitiesBlockGen2V2";
import type { VuCompanyLocksGen2V2 } from "./VuCompanyLocksGen2V2";
import type { VuEventsAndFaultsBlockGen2 } from "./VuEventsAndFaultsBlockGen2";
import type { VuOverviewBlockGen2V2 } from "./VuOverviewBlockGen2V2";

export type VuGen2V2Blocks = { vuOverview: VuOverviewBlockGen2V2, vuActivities: Array<VuActivitiesBlockGen2V2>, vuEventsAndFaults: Array<VuEventsAndFaultsBlockGen2>, vuCompanyLocks: Array<VuCompanyLocksGen2V2>, };
