// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { ExtendedSerialNumber } from "./ExtendedSerialNumber";
import type { Name } from "./Name";
import type { TimeReal } from "./TimeReal";
import type { VuApprovalNumber } from "./VuApprovalNumber";
import type { VuPartNumber } from "./VuPartNumber";
import type { VuSoftwareIdentification } from "./VuSoftwareIdentification";

export type VuIdentification = { vuManufacturerName: Name, vuManufacturerAddress: Address, vuPartNumber: VuPartNumber, vuSerialNumber: ExtendedSerialNumber, vuSoftwareIdentification: VuSoftwareIdentification, vuManufacturingDate: TimeReal, vuApprovalNumber: VuApprovalNumber, };
