// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { ExtendedSerialNumberGen2 } from "./ExtendedSerialNumberGen2";
import type { GenerationGen2 } from "./GenerationGen2";
import type { Name } from "./Name";
import type { TimeReal } from "./TimeReal";
import type { VuAbilityGen2 } from "./VuAbilityGen2";
import type { VuApprovalNumberGen2 } from "./VuApprovalNumberGen2";
import type { VuDigitalMapVersion } from "./VuDigitalMapVersion";
import type { VuPartNumber } from "./VuPartNumber";
import type { VuSoftwareIdentification } from "./VuSoftwareIdentification";

export type VuIdentificationGen2V2 = { vuManufacturerName: Name, vuManufacturerAddress: Address, vuPartNumber: VuPartNumber, vuSerialNumber: ExtendedSerialNumberGen2, vuSoftwareIdentification: VuSoftwareIdentification, vuManufacturingDate: TimeReal, vuApprovalNumber: VuApprovalNumberGen2, vuGeneration: GenerationGen2, vuAbility: VuAbilityGen2, vuDigitalMapVersion: VuDigitalMapVersion, };
