// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FullCardNumberAndGenerationGen2 } from "./FullCardNumberAndGenerationGen2";

export type VuITSConsentRecordGen2 = { cardNumberAndGen: FullCardNumberAndGenerationGen2 | null, consent: boolean, };
