// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Speed } from "./Speed";
import type { TimeReal } from "./TimeReal";

export type VuOverSpeedingControlDataGen2 = { lastOverspeedControlTime: TimeReal | null, firstOverspeedSince: TimeReal | null, numberOfOverspeedSince: Speed | null, };
