// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventFaultRecordPurpose } from "./EventFaultRecordPurpose";
import type { EventFaultTypeGen2 } from "./EventFaultTypeGen2";
import type { FullCardNumberAndGenerationGen2 } from "./FullCardNumberAndGenerationGen2";
import type { SimilarEventsNumber } from "./SimilarEventsNumber";
import type { Speed } from "./Speed";
import type { TimeReal } from "./TimeReal";

export type VuOverSpeedingEventRecordGen2 = { eventType: EventFaultTypeGen2, eventRecordPurpose: EventFaultRecordPurpose, eventBeginTime: TimeReal, eventEndTime: TimeReal, maxSpeedValue: Speed, averageSpeedValue: Speed, cardNumberAndGenDriverSlotBegin: FullCardNumberAndGenerationGen2 | null, similarEventsNumber: SimilarEventsNumber, };
