// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CertificateGen2 } from "./CertificateGen2";
import type { VehicleIdentificationNumber } from "./VehicleIdentificationNumber";
import type { VehicleRegistrationNumber } from "./VehicleRegistrationNumber";

/**
 * [VuOverviewBlock: appendix 2.183.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e28866)
 */
export type VuOverviewBlock = { memberStateCertificateRecordArray: Array<CertificateGen2>, vuCertificateRecordArray: Array<CertificateGen2>, vehicleIdentificationNumberRecordArray: Array<VehicleIdentificationNumber>, vehicleRegistrationNumberRecordArray: Array<VehicleRegistrationNumber>, };
