// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventFaultRecordPurpose } from "./EventFaultRecordPurpose";
import type { EventFaultType } from "./EventFaultType";
import type { FullCardNumber } from "./FullCardNumber";
import type { SimilarEventsNumber } from "./SimilarEventsNumber";
import type { Speed } from "./Speed";
import type { TimeReal } from "./TimeReal";

/**
 * [VuOverSpeedingEventRecord: appendix 2.215.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e28097)
 */
export type VuOverSpeedingEventRecord = { eventType: EventFaultType, eventRecordPurpose: EventFaultRecordPurpose, eventBeginTime: TimeReal, eventEndTime: TimeReal, maxSpeedValue: Speed, averageSpeedValue: Speed, cardNumberDriverSlot: FullCardNumber, similarEventsNumber: SimilarEventsNumber, };
