// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardSlotsStatus } from "./CardSlotsStatus";
import type { CertificateGen2 } from "./CertificateGen2";
import type { CurrentDateTime } from "./CurrentDateTime";
import type { SignatureGen2 } from "./SignatureGen2";
import type { VehicleIdentificationNumber } from "./VehicleIdentificationNumber";
import type { VehicleRegistrationNumber } from "./VehicleRegistrationNumber";
import type { VuCompanyLocksGen2 } from "./VuCompanyLocksGen2";
import type { VuControlActivityGen2 } from "./VuControlActivityGen2";
import type { VuDownloadActivityDataGen2 } from "./VuDownloadActivityDataGen2";
import type { VuDownloadablePeriod } from "./VuDownloadablePeriod";

export type VuOverviewBlockGen2 = { memberStateCertificateRecordArray: Array<CertificateGen2>, vuCertificateRecordArray: Array<CertificateGen2>, vehicleIdentificationNumberRecordArray: Array<VehicleIdentificationNumber>, vehicleRegistrationNumberRecordArray: Array<VehicleRegistrationNumber>, currentDateTimeRecordArray: Array<CurrentDateTime>, vuDownloadablePeriodRecordArray: Array<VuDownloadablePeriod>, cardSlotsStatusRecordArray: Array<CardSlotsStatus>, vuDownloadActivityDataRecordArray: Array<VuDownloadActivityDataGen2>, vuCompanyLocksRecordArray: Array<VuCompanyLocksGen2>, vuControlActivityRecordArray: Array<VuControlActivityGen2>, signatureRecordArray: Array<SignatureGen2>, };
