// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardSlotsStatus } from "./CardSlotsStatus";
import type { CertificateGen2 } from "./CertificateGen2";
import type { SignatureGen2 } from "./SignatureGen2";
import type { TimeReal } from "./TimeReal";
import type { VehicleIdentificationNumber } from "./VehicleIdentificationNumber";
import type { VehicleRegistrationNumberGen2V2 } from "./VehicleRegistrationNumberGen2V2";
import type { VuCompanyLocksRecordGen2 } from "./VuCompanyLocksRecordGen2";
import type { VuControlActivityRecordGen2 } from "./VuControlActivityRecordGen2";
import type { VuDownloadActivityDataGen2 } from "./VuDownloadActivityDataGen2";
import type { VuDownloadablePeriod } from "./VuDownloadablePeriod";

/**
 * [VuOverviewBlock: appendix 2.183.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e28866)
 */
export type VuOverviewBlockGen2V2 = { 
/**
 * Member state certificate
 */
memberStateCertificateRecordArray: Array<CertificateGen2>, 
/**
 * VU certificate
 */
vuCertificateRecordArray: Array<CertificateGen2>, 
/**
 * Vehicle identification
 */
vehicleIdentificationNumberRecordArray: Array<VehicleIdentificationNumber>, 
/**
 * Vehicle registration number
 */
vehicleRegistrationNumberRecordArray: Array<VehicleRegistrationNumberGen2V2>, 
/**
 * VU current date and time
 */
currentDateTimeRecordArray: Array<TimeReal>, 
/**
 * Downloadable period
 */
vuDownloadablePeriodRecordArray: Array<VuDownloadablePeriod>, 
/**
 * Type of cards inserted in the VU
 */
cardSlotsStatusRecordArray: Array<CardSlotsStatus>, 
/**
 * Previous VU download
 */
vuDownloadActivityDataRecordArray: Array<VuDownloadActivityDataGen2>, 
/**
 * All company locks stored.
 */
vuCompanyLocksRecordArray: Array<VuCompanyLocksRecordGen2>, 
/**
 * All control records stored in the VU.
 */
vuControlActivityRecordArray: Array<VuControlActivityRecordGen2>, 
/**
 * ECC signature of all preceding data except the certificates
 */
signatureRecordArray: Array<SignatureGen2>, };
