// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FullCardNumberAndGenerationGen2 } from "./FullCardNumberAndGenerationGen2";
import type { PlaceRecordGen2 } from "./PlaceRecordGen2";

export type VuPlaceDailyWorkPeriodGen2 = { fullCardNumberAndGeneration: FullCardNumberAndGenerationGen2 | null, placeRecord: PlaceRecordGen2, };
