// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FullCardNumber } from "./FullCardNumber";
import type { PlaceRecord } from "./PlaceRecord";

/**
 * [VuPlaceDailyWorkPeriodRecord: appendix 2.219.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e28313)
 */
export type VuPlaceDailyWorkPeriodRecord = { fullCardNumber: FullCardNumber, placeRecord: PlaceRecord, };
