// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FullCardNumberAndGenerationGen2 } from "./FullCardNumberAndGenerationGen2";
import type { PlaceAuthRecord } from "./PlaceAuthRecord";

/**
 * [VuPlaceDailyWorkPeriod: appendix 2.219.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e28313)
 */
export type VuPlaceDailyWorkPeriodRecordGen2V2 = { fullCardNumberAndGeneration: FullCardNumberAndGenerationGen2 | null, placeRecord: PlaceAuthRecord, };
