// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventFaultRecordPurpose } from "./EventFaultRecordPurpose";
import type { EventFaultTypeGen2 } from "./EventFaultTypeGen2";
import type { FullCardNumberAndGenerationGen2 } from "./FullCardNumberAndGenerationGen2";
import type { SimilarEventsNumber } from "./SimilarEventsNumber";
import type { TimeReal } from "./TimeReal";

/**
 * [VuPowerSupplyInterruptionRecord: appendix 2.240.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e29420)
 */
export type VuPowerSupplyInterruptionRecordGen2 = { eventType: EventFaultTypeGen2, eventRecordPurpose: EventFaultRecordPurpose, eventBeginTime: TimeReal, eventEndTime: TimeReal, cardNumberAndGenDriverSlotBegin: FullCardNumberAndGenerationGen2 | null, cardNumberAndGenDriverSlotEnd: FullCardNumberAndGenerationGen2 | null, cardNumberAndGenCodriverSlotBegin: FullCardNumberAndGenerationGen2 | null, cardNumberAndGenCodriverSlotEnd: FullCardNumberAndGenerationGen2 | null, similarEventsNumber: SimilarEventsNumber, };
