// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignatureGen2 } from "./SignatureGen2";
import type { VuDetailedSpeedBlock } from "./VuDetailedSpeedBlock";

export type VuSpeedBlockGen2 = { vuDetailedSpeedBlockRecordArray: Array<VuDetailedSpeedBlock>, signatureRecordArray: Array<SignatureGen2>, };
