// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VuTimeAdjustmentRecord } from "./VuTimeAdjustmentRecord";

/**
 * [VuTimeAdjustmentData: appendix 2.229.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e28675)
 */
export type VuTimeAdjustmentData = { noOfVuTimeAdjRecords: number, vuTimeAdjustmentRecords: Array<VuTimeAdjustmentRecord>, };
