// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardStructureVersion } from "./CardStructureVersion";
import type { EquipmentType } from "./EquipmentType";

export type WorkshopCardApplicationIdentification = { typeOfTachographCardId: EquipmentType, cardStructureVersion: CardStructureVersion, noOfEventsPerType: number, noOfFaultsPerType: number, activityStructureLength: number, noOfCardVehicleRecords: number, noOfCardPlaceRecords: number, noOfCalibrationRecords: number, };
