import type { VuData } from "./bindings/VuData";
import type { CardData } from "./bindings/CardData";
import type { TachoFileType } from "./bindings/TachoFileType";
/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function detectTachoFileType(bytes: Buffer): TachoFileType

export declare function parseCard(bytes: Buffer): CardData

export declare function parseVu(bytes: Buffer): VuData
