import type { VuData } from "./bindings/VuData";
import type { CardData } from "./bindings/CardData";
import type { TachoFileType } from "./bindings/TachoFileType";
/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function parseVu(bytes: Buffer): VuData
export declare function parseCard(bytes: Buffer): CardData
export declare function detectTachoFileType(bytes: Buffer): TachoFileType
