/* auto-generated by NAPI-RS */
/* eslint-disable */
/** [ActivityChangeInfo: appendix 2.1.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e16027) */
export interface ActivityChangeInfo {
  slot: ActivityChangeInfoSlot
  drivingStatus: ActivityChangeInfoDrivingStatus
  slotStatus: ActivityChangeInfoCardStatusSlot
  activity: ActivityChangeInfoCardActivity
  minutes: number
}

export declare const enum ActivityChangeInfoCardActivity {
  BreakRest = 'BreakRest',
  Availability = 'Availability',
  Work = 'Work',
  Driving = 'Driving'
}

export declare const enum ActivityChangeInfoCardStatusSlot {
  Inserted = 'Inserted',
  NotInserted = 'NotInserted'
}

export declare const enum ActivityChangeInfoDrivingStatus {
  Single = 'Single',
  Crew = 'Crew'
}

export declare const enum ActivityChangeInfoSlot {
  Driver = 'Driver',
  CoDriver = 'CoDriver'
}

/** [Address: appendix 2.2.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e16375) */
export interface Address {
  codePage: number
  address: string
}

export interface ApplicationIdentificationGen2 {
  driverCardApplicationIdentification: DriverCardApplicationIdentificationGen2
}

export interface BcdString {
  value: string
}

/** [CalibrationPurpose: appendix 2.8.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e16597) */
export declare const enum CalibrationPurpose {
  Reserved = 'Reserved',
  Activation = 'Activation',
  FirstInstallation = 'FirstInstallation',
  Installation = 'Installation',
  PeriodicInspection = 'PeriodicInspection'
}

/** [CalibrationPurpose: appendix 2.8.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e16597) */
export declare const enum CalibrationPurposeGen2 {
  Reserved = 'Reserved',
  Activation = 'Activation',
  FirstInstallation = 'FirstInstallation',
  Installation = 'Installation',
  PeriodicInspection = 'PeriodicInspection',
  EntryOfVRNByCompany = 'EntryOfVRNByCompany',
  TimeAdjustmentWithoutCalibration = 'TimeAdjustmentWithoutCalibration',
  RFU = 'RFU',
  ManufacturerSpecific = 'ManufacturerSpecific'
}

/** [CardDriverActivity: appendix 2.9.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e16718) */
export interface CardActivityDailyRecord {
  activityPreviousRecordLength: CardActivityLengthRange
  activityRecordLength: CardActivityLengthRange
  activityRecordDate: TimeReal
  activityDailyPresenceCounter: DailyPresenceCounter
  activityDayDistance: Distance
  activityChangeInfo: Array<ActivityChangeInfo>
}

/** [CardApprovalNumber: appendix 2.11.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e16800) */
export interface CardApprovalNumber {
  value: string
}

/** [CardChipIdentification: appendix 2.1.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e16027) */
export interface CardChipIdentification {
  cardChipIdentificationNumber: Array<number>
  cardChipIdentificationSignature: Array<number>
}

/** [CardConsecutiveIndex: appendix 2.14.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e16973) */
export interface CardConsecutiveIndex {
  value: string
}

/** [CardControlActivityDataRecord appendix 2.15.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17002) */
export interface CardControlActivityDataRecord {
  controlType: ControlType
  controlTime?: TimeReal
  controlCardNumber: FullCardNumber
  controlVehicleRegistration: VehicleRegistrationIdentification
  controlDownloadPeriodBegin?: TimeReal
  controlDownloadPeriodEnd?: TimeReal
}

/** [CardControlActivityDataRecord appendix 2.15.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17002) */
export interface CardControlActivityDataRecordGen2 {
  controlType: ControlTypeGen2
  controlTime?: TimeReal
  controlCardNumber: FullCardNumberGen2
  controlVehicleRegistration: VehicleRegistrationIdentification
  controlDownloadPeriodBegin?: TimeReal
  controlDownloadPeriodEnd?: TimeReal
}

/** [CardCurrentUse appendix 2.16.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17059) */
export interface CardCurrentUse {
  sessionOpenTime: TimeReal
  sessionOpenVehicle: VehicleRegistrationIdentification
}

export type CardData =
  | { type: 'Gen1', gen1Blocks: CardGen1Blocks }
  | { type: 'Gen2', gen1Blocks: CardGen1Blocks, gen2Blocks: CardGen2Blocks }
  | { type: 'Gen2V2', gen1Blocks: CardGen1Blocks, gen2Blocks: CardGen2Blocks, gen2V2Blocks: CardGen2V2Blocks }

/** [CardDownload: appendix 4.2.2.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e41651) */
export interface CardDownload {
  lastCardDownload?: LastCardDownload
}

/** [CardDriverActivity: appendix 2.17.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17092) */
export interface CardDriverActivity {
  activityPointerOldestDayRecord: number
  activityPointerNewestRecord: number
  activityDailyRecords: Array<CardActivityDailyRecord>
}

/** EF Block page 281 */
export interface CardDrivingLicenceInfo {
  cardDrivingLicenceInformation: CardDrivingLicenceInformation
}

/** [CardDrivingLicenceInformation: appendix 2.18.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17139) */
export interface CardDrivingLicenceInformation {
  drivingLicenceIssuingAuthority: Name
  drivingLicenceIssuingNation: NationNumeric
  drivingLicenceNumber: string
}

/** [CardEventData: appendix 2.19.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17180) */
export interface CardEventData {
  records: Array<Array<CardEventRecord>>
}

/** [CardEventData: appendix 2.19.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17180) */
export interface CardEventDataGen2 {
  records: Array<Array<CardEventRecordGen2>>
}

/** [CardEventRecord: appendix 2.20.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17247) */
export interface CardEventRecord {
  eventType: EventFaultType
  eventBeginTime: TimeReal
  eventEndTime: TimeReal
  eventVehicleRegistration: VehicleRegistrationIdentification
}

/** [CardEventRecord: appendix 2.20.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17247) */
export interface CardEventRecordGen2 {
  eventType: EventFaultTypeGen2
  eventBeginTime: TimeReal
  eventEndTime: TimeReal
  eventVehicleRegistration: VehicleRegistrationIdentification
}

/** [CardFaultData: appendix 2.22.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17340) */
export interface CardFaultData {
  records: Array<Array<CardFaultRecord>>
}

/** [CardFaultData: appendix 2.22.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17340) */
export interface CardFaultDataGen2 {
  records: Array<Array<CardFaultRecordGen2>>
}

/** [CardFaultData: appendix 2.21.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17292) */
export interface CardFaultRecord {
  faultType: EventFaultType
  faultBeginTime: TimeReal
  faultEndTime: TimeReal
  faultVehicleRegistration: VehicleRegistrationIdentification
}

/** [CardFaultData: appendix 2.21.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17292) */
export interface CardFaultRecordGen2 {
  faultType: EventFaultTypeGen2
  faultBeginTime: TimeReal
  faultEndTime: TimeReal
  faultVehicleRegistration: VehicleRegistrationIdentification
}

export interface CardGen1Blocks {
  cardIccIdentification: CardIccIdentification
  cardChipIdentification: CardChipIdentification
  applicationIdentification: DriverCardApplicationIdentification
  applicationIdentificationSignature: Signature
  cardCertificate: Certificate
  memberStateCertificate: Certificate
  identification: Identification
  identificationSignature: Signature
  cardDownload?: CardDownload
  cardDownloadSignature?: Signature
  driverLicenceInfo?: CardDrivingLicenceInformation
  driverLicenceInfoSignature?: Signature
  eventsData: CardEventData
  eventsDataSignature: Signature
  faultsData: CardFaultData
  faultsDataSignature: Signature
  driverActivityData: DriverActivityData
  driverActivityDataSignature: Signature
  vehiclesUsed: CardVehiclesUsed
  vehiclesUsedSignature: Signature
  places: CardPlaceDailyWorkPeriod
  placesSignature: Signature
  currentUsage?: CurrentUsage
  currentUsageSignature?: Signature
  controlActivityData: CardControlActivityDataRecord
  controlActivityDataSignature: Signature
  specificConditions: SpecificConditions
  specificConditionsSignature: Signature
}

export interface CardGen2Blocks {
  cardIccIdentification: CardIccIdentificationGen2
  cardChipIdentification: CardChipIdentification
  applicationIdentification: DriverCardApplicationIdentificationGen2
  applicationIdentificationSignature: SignatureGen2
  cardSignCertificate: CertificateGen2
  caCertificate: CertificateGen2
  linkCertificate: CertificateGen2
  identification: Identification
  identificationSignature: SignatureGen2
  cardDownload?: CardDownload
  cardDownloadSignature?: SignatureGen2
  driverLicenceInfo?: CardDrivingLicenceInformation
  driverLicenceInfoSignature?: SignatureGen2
  eventsData: CardEventDataGen2
  eventsDataSignature: SignatureGen2
  faultsData: CardFaultDataGen2
  faultsDataSignature: SignatureGen2
  driverActivityData: DriverActivityData
  driverActivityDataSignature: SignatureGen2
  vehiclesUsed: CardVehiclesUsedGen2
  vehiclesUsedSignature: SignatureGen2
  places: CardPlaceDailyWorkPeriodGen2
  placesSignature: SignatureGen2
  currentUsage?: CurrentUsage
  currentUsageSignature?: SignatureGen2
  controlActivityData: CardControlActivityDataRecordGen2
  controlActivityDataSignature: SignatureGen2
  specificConditions: SpecificConditionsGen2
  specificConditionsSignature: SignatureGen2
  vehicleUnitsUsed: CardVehicleUnitsUsedGen2
  vehicleUnitsUsedSignature: SignatureGen2
  gnssAccumulatedDriving: GnssAccumulatedDrivingGen2
  gnssPlacesSignature: SignatureGen2
}

export interface CardGen2V2Blocks {

}

/** [CardIccIdentification: appendix 2.23.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17372) */
export interface CardIccIdentification {
  clockStop: number
  cardExtendedSerialNumber: ExtendedSerialNumber
  cardApprovalNumber: CardApprovalNumber
  cardPersonaliserId: ManufacturerCode
  embedderIcAssemblerId: EmbedderIcAssemblerId
  icIdentifier: Array<number>
}

/** [CardIccIdentification: appendix 2.23.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17372) */
export interface CardIccIdentificationGen2 {
  clockStop: number
  cardExtendedSerialNumber: ExtendedSerialNumberGen2
  cardApprovalNumber: CardApprovalNumber
  cardPersonaliserId: ManufacturerCode
  embedderIcAssemblerId: EmbedderIcAssemblerId
  icIdentifier: Array<number>
}

/** [CardIdentification: appendix 2.24.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17430) */
export interface CardIdentification {
  cardIssuingMemberState: NationNumeric
  cardNumber: CardNumber
  cardIssuingAuthorityName: Name
  cardIssueDate: TimeReal
  cardValidityBegin: TimeReal
  cardExpiryDate: TimeReal
}

/** [CardNumber: appendix 2.26.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17629) */
export type CardNumber =
  | { type: 'Driver', driverIdentification: string, cardReplacementIndex: CardReplacementIndex, cardRenewalIndex: CardRenewalIndex }
  | { type: 'Owner', ownerIdentification: string, cardConsecutiveIndex: CardConsecutiveIndex, cardReplacementIndex: CardReplacementIndex, cardRenewalIndex: CardRenewalIndex }
  | { type: 'None' }

/** [CardPlaceDailyWorkPeriod: appendix 2.27.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17729) */
export interface CardPlaceDailyWorkPeriod {
  placePointerNewestRecord: NoOfCardPlaceRecords
  placeRecords: Array<PlaceRecord>
}

/** [CardPlaceDailyWorkPeriod: appendix 2.27.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17729) */
export interface CardPlaceDailyWorkPeriodGen2 {
  placePointerNewestRecord: NoOfCardPlaceRecordsGen2
  placeRecords: Array<PlaceRecordGen2>
}

/** [CardRenewalIndex: appendix 2.30.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17812) */
export interface CardRenewalIndex {
  value: string
}

/** [CardReplacementIndex: appendix 2.31.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17853) */
export interface CardReplacementIndex {
  value: string
}

/** [CardSlotNumber: appendix 2.33.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17911) */
export declare const enum CardSlotNumber {
  DriverSlot = 'DriverSlot',
  CoDriverSlot = 'CoDriverSlot'
}

/** [CardSlotsStatus: appendix 2.34.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e17939) */
export interface CardSlotsStatus {
  codriver: CardSlotStatus
  driver: CardSlotStatus
}

export declare const enum CardSlotStatus {
  NoCardInserted = 'NoCardInserted',
  DriverCardInserted = 'DriverCardInserted',
  WorkshopCardInserted = 'WorkshopCardInserted',
  ControlCardInserted = 'ControlCardInserted',
  CompanyCardInserted = 'CompanyCardInserted'
}

/** [CardStructureVersion: appendix 2.36.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e18081) */
export declare const enum CardStructureVersion {
  Gen1 = 'Gen1',
  Gen2 = 'Gen2',
  Gen2V2 = 'Gen2V2'
}

/** [CardVehicleRecord: appendix 2.37.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e18163) */
export interface CardVehicleRecord {
  vehicleOdometerBegin: OdometerShort
  vehicleOdometerEnd: OdometerShort
  vehicleFirstUse: TimeReal
  vehicleLastUse: TimeReal
  vehicleRegistration: VehicleRegistrationIdentification
  vuDataBlockCounter: VuDataBlockCounter
}

/** [CardVehicleRecord: appendix 2.37.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e18163) */
export interface CardVehicleRecordGen2 {
  vehicleOdometerBegin: OdometerShort
  vehicleOdometerEnd: OdometerShort
  vehicleFirstUse: TimeReal
  vehicleLastUse: TimeReal
  vehicleRegistration: VehicleRegistrationIdentification
  vuDataBlockCounter: VuDataBlockCounter
  vehicleIdentificationNumber: VehicleIdentificationNumber
}

/** [CardVehiclesUsed: appendix 2.38.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e18302) */
export interface CardVehiclesUsed {
  vehiclePointerNewestRecord: number
  cardVehicleRecords: Array<CardVehicleRecord>
}

/** [CardVehiclesUsed: appendix 2.38.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e18302) */
export interface CardVehiclesUsedGen2 {
  vehiclePointerNewestRecord: number
  cardVehicleRecords: Array<CardVehicleRecordGen2>
}

/** [CardVehicleUnitRecord: appendix 2.39.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e18302) */
export interface CardVehicleUnitRecordGen2 {
  timeStamp: TimeReal
  manufacturerCode: ManufacturerCode
  deviceId: number
  vuSoftwareVersion: VuSoftwareVersion
}

/** [CardVehicleUnitsUsed: appendix 2.40.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e18350) */
export interface CardVehicleUnitsUsedGen2 {
  noOfCardVehicleUnitRecords: NoOfCardVehicleUnitRecordsGen2
  cardVehicleUnitRecords: Array<CardVehicleUnitRecordGen2>
}

/** [Certificate: appendix 2.41.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e18396) */
export interface Certificate {
  value: Array<number>
}

/** [Certificate: appendix 2.41.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e18396) */
export interface CertificateGen2 {
  value: Array<number>
}

/** [ControlType: appendix 2.53.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e19148) */
export interface ControlType {
  cardDownloading: boolean
  vuDownloading: boolean
  printing: boolean
  display: boolean
}

/** [ControlType: appendix 2.53.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e19148) */
export interface ControlTypeGen2 {
  cardDownloading: boolean
  vuDownloading: boolean
  printing: boolean
  display: boolean
  roadsideCalibrationChecking: boolean
}

/** [CurrentDateTime: appendix 2.54.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e19437) */
export interface CurrentDateTime {
  value: Date
}

/** EF Block page 281 */
export interface CurrentUsage {
  cardCurrentUse: CardCurrentUse
}

/** [DailyPresenceCounter: appendix 2.56.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e19510) */
export interface DailyPresenceCounter {
  value: number
}

/** [Datef: appendix 2.63.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e20100) */
export interface Datef {
  year: number
  month: number
  day: number
}

export interface DateOfDayDownloadedGen2 {
  value: Date
}

export declare function detectTachoFileType(bytes: Buffer): TachoFileType

/** [Distance: appendix 2.60.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e19665) */
export interface Distance {
  /** Value in km in the operational range 0 to 9 999 km. */
  km: number
}

/** EF Block page 281 */
export interface DriverActivityData {
  cardDriverActivity: CardDriverActivity
}

/** [DriverCardApplicationIdentification: appendix 2.61.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e19751) */
export interface DriverCardApplicationIdentification {
  typeOfTachographCardId: EquipmentType
  cardStructureVersion: Array<number>
  noOfEventsPerType: number
  noOfFaultsPerType: number
  activityStructureLength: number
  noOfCardVehicleRecords: number
  noOfCardPlaceRecords: number
}

/** [DriverCardApplicationIdentification: appendix 2.61.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e19751) */
export interface DriverCardApplicationIdentificationGen2 {
  typeOfTachographCardId: EquipmentTypeGen2
  cardStructureVersion: CardStructureVersion
  noOfEventsPerType: NoOfEventsPerTypeGen2
  noOfFaultsPerType: NoOfFaultsPerTypeGen2
  activityStructureLength: CardActivityLengthRange
  noOfCardVehicleRecords: NoOfCardVehicleRecordsGen2
  noOfCardPlaceRecords: NoOfCardPlaceRecordsGen2
  noOfGnssAdRecords: NoOfGnssAdRecordsGen2
  noOfSpecificConditionRecords: NoOfSpecificConditionRecordsGen2
  noOfCardVehicleUnitRecords: NoOfCardVehicleUnitRecordsGen2
}

/** [DriverCardHolderIdentification: appendix 2.62.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e19928) */
export interface DriverCardHolderIdentification {
  cardHolderNumber: HolderName
  cardHolderBirthDate: Datef
  cardHolderPreferredLanguage: Language
}

/** [EmbedderIcAssemblerId: appendix 2.65.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e20005) */
export interface EmbedderIcAssemblerId {
  countryCode: Ia5String
  moduleEmbedder: number
  manufacturerInformation: number
}

/** [EntryTypeDailyWorkPeriod: appendix 2.66.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e20044) */
export declare const enum EntryTypeDailyWorkPeriod {
  BeginRelatedTimeCardInsertionTimeOrTimeOfEntry = 'BeginRelatedTimeCardInsertionTimeOrTimeOfEntry',
  EndRelatedTimeCardWithdrawalTimeOrTimeOfEntry = 'EndRelatedTimeCardWithdrawalTimeOrTimeOfEntry',
  BeginRelatedTimeManuallyEntered = 'BeginRelatedTimeManuallyEntered',
  EndRelatedTimeManuallyEntered = 'EndRelatedTimeManuallyEntered',
  BeginRelatedTimeAssumedByVU = 'BeginRelatedTimeAssumedByVU',
  EndRelatedTimeAssumedByVU = 'EndRelatedTimeAssumedByVU'
}

/** [EntryTypeDailyWorkPeriod: appendix 2.66.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e20044) */
export declare const enum EntryTypeDailyWorkPeriodGen2 {
  BeginRelatedTimeCardInsertionTimeOrTimeOfEntry = 'BeginRelatedTimeCardInsertionTimeOrTimeOfEntry',
  EndRelatedTimeCardWithdrawalTimeOrTimeOfEntry = 'EndRelatedTimeCardWithdrawalTimeOrTimeOfEntry',
  BeginRelatedTimeManuallyEntered = 'BeginRelatedTimeManuallyEntered',
  EndRelatedTimeManuallyEntered = 'EndRelatedTimeManuallyEntered'
}

/** [EquipmentType: appendix 2.67.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e20100) */
export declare const enum EquipmentType {
  Reserved = 'Reserved',
  DriverCard = 'DriverCard',
  WorkshopCard = 'WorkshopCard',
  ControlCard = 'ControlCard',
  CompanyCard = 'CompanyCard',
  ManufacturingCard = 'ManufacturingCard',
  VehicleUnit = 'VehicleUnit',
  MotionSensor = 'MotionSensor',
  RFU = 'RFU'
}

export declare const enum EquipmentTypeGen2 {
  Reserved = 'Reserved',
  DriverCard = 'DriverCard',
  WorkshopCard = 'WorkshopCard',
  ControlCard = 'ControlCard',
  CompanyCard = 'CompanyCard',
  ManufacturingCard = 'ManufacturingCard',
  VehicleUnit = 'VehicleUnit',
  MotionSensor = 'MotionSensor',
  GNSSFacility = 'GnssFacility',
  RemoteCommunicationDevice = 'RemoteCommunicationDevice',
  ITSinterfaceModule = 'ItSinterfaceModule',
  Plaque = 'Plaque',
  M1N1Adapter = 'M1N1Adapter',
  CAERCA = 'Caerca',
  CAMSCA = 'Camsca',
  ExternalGNSSConnection = 'ExternalGnssConnection',
  Unused = 'Unused',
  DriverCardSign = 'DriverCardSign',
  WorkshopCardSign = 'WorkshopCardSign',
  VehicleUnitSign = 'VehicleUnitSign',
  RFU = 'Rfu'
}

/** [EventFaultRecordPurpose: appendix 2.69.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e20262) */
export declare const enum EventFaultRecordPurpose {
  OneOfTenMostRecentOrLast = 'OneOfTenMostRecentOrLast',
  LongestEventLastTenDays = 'LongestEventLastTenDays',
  OneOfFiveLongestEventsLastYear = 'OneOfFiveLongestEventsLastYear',
  LastEventLastTenDays = 'LastEventLastTenDays',
  MostSeriousEventLastTenDays = 'MostSeriousEventLastTenDays',
  OneOfFiveMostSeriousEventsLastYear = 'OneOfFiveMostSeriousEventsLastYear',
  FirstEventAfterLastCalibration = 'FirstEventAfterLastCalibration',
  ActiveOrOngoing = 'ActiveOrOngoing',
  RFU = 'RFU',
  ManufacturerSpecific = 'ManufacturerSpecific'
}

/** [EventFaultType: appendix 2.70.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e20338) */
export declare const enum EventFaultType {
  NoFurtherDetails = 'NoFurtherDetails',
  InsertionOfNonValidCard = 'InsertionOfNonValidCard',
  CardConflict = 'CardConflict',
  TimeOverlap = 'TimeOverlap',
  DrivingWithoutAppropriateCard = 'DrivingWithoutAppropriateCard',
  CardInsertionWhileDriving = 'CardInsertionWhileDriving',
  LastCardSessionNotCorrectlyClosed = 'LastCardSessionNotCorrectlyClosed',
  OverSpeeding = 'OverSpeeding',
  PowerSupplyInterruption = 'PowerSupplyInterruption',
  MotionDataError = 'MotionDataError',
  VehicleMotionConflict = 'VehicleMotionConflict',
  VUSecurityBreachAttemptNoFurtherDetails = 'VUSecurityBreachAttemptNoFurtherDetails',
  MotionSensorAuthenticationFailure = 'MotionSensorAuthenticationFailure',
  TachographCardAuthenticationFailure = 'TachographCardAuthenticationFailure',
  UnauthorizedChangeOfMotionSensor = 'UnauthorizedChangeOfMotionSensor',
  CardDataInputIntegrityError = 'CardDataInputIntegrityError',
  StoredUserDataIntegrityError = 'StoredUserDataIntegrityError',
  InternalDataTransferError = 'InternalDataTransferError',
  UnauthorizedCaseOpening = 'UnauthorizedCaseOpening',
  HardwareSabotage = 'HardwareSabotage',
  SensorSecurityBreachAttemptNoFurtherDetails = 'SensorSecurityBreachAttemptNoFurtherDetails',
  SensorAuthenticationFailure = 'SensorAuthenticationFailure',
  SensorStoredDataIntegrityError = 'SensorStoredDataIntegrityError',
  SensorInternalDataTransferError = 'SensorInternalDataTransferError',
  SensorUnauthorizedCaseOpening = 'SensorUnauthorizedCaseOpening',
  SensorHardwareSabotage = 'SensorHardwareSabotage',
  ControlDeviceFaultNoFurtherDetails = 'ControlDeviceFaultNoFurtherDetails',
  VUInternalFault = 'VUInternalFault',
  PrinterFault = 'PrinterFault',
  DisplayFault = 'DisplayFault',
  DownloadingFault = 'DownloadingFault',
  SensorFault = 'SensorFault',
  RFU = 'RFU',
  ManufacturerSpecific = 'ManufacturerSpecific'
}

/** [EventFaultType: appendix 2.70.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e20338) */
export declare const enum EventFaultTypeGen2 {
  NoFurtherDetails = 'NoFurtherDetails',
  InsertionOfNonValidCard = 'InsertionOfNonValidCard',
  CardConflict = 'CardConflict',
  TimeOverlap = 'TimeOverlap',
  DrivingWithoutAppropriateCard = 'DrivingWithoutAppropriateCard',
  CardInsertionWhileDriving = 'CardInsertionWhileDriving',
  LastCardSessionNotCorrectlyClosed = 'LastCardSessionNotCorrectlyClosed',
  OverSpeeding = 'OverSpeeding',
  PowerSupplyInterruption = 'PowerSupplyInterruption',
  MotionDataError = 'MotionDataError',
  VehicleMotionConflict = 'VehicleMotionConflict',
  TimeConflict = 'TimeConflict',
  CommunicationErrorWithRemoteCommunicationFacility = 'CommunicationErrorWithRemoteCommunicationFacility',
  AbsenceOfPositionInfoFromGNSSReceiver = 'AbsenceOfPositionInfoFromGNSSReceiver',
  CommunicationErrorWithExternalGNSSFacility = 'CommunicationErrorWithExternalGNSSFacility',
  VUSecurityBreachAttemptNoFurtherDetails = 'VUSecurityBreachAttemptNoFurtherDetails',
  MotionSensorAuthenticationFailure = 'MotionSensorAuthenticationFailure',
  TachographCardAuthenticationFailure = 'TachographCardAuthenticationFailure',
  UnauthorizedChangeOfMotionSensor = 'UnauthorizedChangeOfMotionSensor',
  CardDataInputIntegrityError = 'CardDataInputIntegrityError',
  StoredUserDataIntegrityError = 'StoredUserDataIntegrityError',
  InternalDataTransferError = 'InternalDataTransferError',
  UnauthorizedCaseOpening = 'UnauthorizedCaseOpening',
  HardwareSabotage = 'HardwareSabotage',
  TamperDetectionOfGNSS = 'TamperDetectionOfGNSS',
  ExternalGNSSFacilityAuthenticationFailure = 'ExternalGNSSFacilityAuthenticationFailure',
  ExternalGNSSFacilityCertificateExpired = 'ExternalGNSSFacilityCertificateExpired',
  SensorSecurityBreachAttemptNoFurtherDetails = 'SensorSecurityBreachAttemptNoFurtherDetails',
  SensorAuthenticationFailure = 'SensorAuthenticationFailure',
  SensorStoredDataIntegrityError = 'SensorStoredDataIntegrityError',
  SensorInternalDataTransferError = 'SensorInternalDataTransferError',
  SensorUnauthorizedCaseOpening = 'SensorUnauthorizedCaseOpening',
  SensorHardwareSabotage = 'SensorHardwareSabotage',
  ControlDeviceFaultNoFurtherDetails = 'ControlDeviceFaultNoFurtherDetails',
  VUInternalFault = 'VUInternalFault',
  PrinterFault = 'PrinterFault',
  DisplayFault = 'DisplayFault',
  DownloadingFault = 'DownloadingFault',
  SensorFault = 'SensorFault',
  InternalGNSSReceiver = 'InternalGNSSReceiver',
  ExternalGNSSFacility = 'ExternalGNSSFacility',
  RemoteCommunicationFacility = 'RemoteCommunicationFacility',
  ITSInterface = 'ITSInterface',
  CardFaultNoFurtherDetails = 'CardFaultNoFurtherDetails',
  RFU = 'RFU',
  ManufacturerSpecific = 'ManufacturerSpecific'
}

/** [ExtendedSealIdentifier: appendix 2.71.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e21276) */
export interface ExtendedSealIdentifierGen2 {
  manufacturerCode: Array<number>
  sealIdentifier: Array<number>
}

/** [ExtendedSerialNumber: appendix 2.72.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e21307) */
export interface ExtendedSerialNumber {
  serialNumber: number
  monthYear: MonthYear
  type: number
  manufacturerCode: ManufacturerCode
}

/** [ExtendedSerialNumber: appendix 2.72.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e21307) */
export interface ExtendedSerialNumberGen2 {
  serialNumber: number
  monthYear: MonthYear
  equipmentType: EquipmentTypeGen2
  manufacturerCode: ManufacturerCode
}

/** [FullCardNumber: appendix 2.73.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e21400) */
export interface FullCardNumber {
  cardType: EquipmentType
  cardIssuingMemberState: NationNumeric
  cardNumber: CardNumber
}

/** [FullCardNumberAndGeneration: appendix 2.74.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e21438) */
export interface FullCardNumberAndGenerationGen2 {
  fullCardNumber: FullCardNumberGen2
  generation: GenerationGen2
}

/** [FullCardNumber: appendix 2.73.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e21400) */
export interface FullCardNumberGen2 {
  cardType: EquipmentTypeGen2
  cardIssuingMemberState: NationNumeric
  cardNumber: CardNumber
}

/** [Generation: appendix 2.75.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e23342) */
export declare const enum GenerationGen2 {
  Generation1 = 'Generation1',
  Generation2 = 'Generation2',
  RFU = 'RFU'
}

/** [GeoCoordinates: appendix 2.76.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e21534) */
export interface GeoCoordinatesGen2 {
  latitude: number
  longitude: number
}

/** [GNSSAccumulatedDriving: appendix 2.79.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e21595) */
export interface GnssAccumulatedDrivingGen2 {
  gnssAdPointerNewestRecord: NoOfGnssAdRecordsGen2
  gnssAccumulatedDrivingRecords: Array<GnssAccumulatedDrivingRecordGen2>
}

/** [GNSSAccumulatedDrivingRecord: appendix 2.79.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e21640) */
export interface GnssAccumulatedDrivingRecordGen2 {
  timeStamp: TimeReal
  gnssPlaceRecord: GnssPlaceRecordGen2
  vehicleOdometerValue: OdometerShort
}

/** [GNSSAccuracy: appendix 2.77.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e21573) */
export interface GnssAccuracyGen2 {
  value: number
}

/** [GNSSPlaceRecord: appendix 2.80.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e21772) */
export interface GnssPlaceRecordGen2 {
  timeStamp: TimeReal
  gnssAccuracy: GnssAccuracyGen2
  geoCoordinates: GeoCoordinatesGen2
}

/** [HolderName: appendix 2.83.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e21860) */
export interface HolderName {
  holderSurname: Name
  holderFirstNames: Name
}

export interface Ia5String {
  value: string
}

/** [Identification: appendix 4.2.2.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e41651) */
export interface Identification {
  cardIdentification: CardIdentification
  driverCardHolderIdentification: DriverCardHolderIdentification
}

/** [KConstantOfRecordingEquipment: appendix 2.85.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e21927) */
export interface KConstantOfRecordingEquipment {
  value: number
}

export interface Language {
  value: string
}

/** [LTyreCircumference: appendix 2.91.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e22169) */
export interface LTyreCircumference {
  value: number
}

/** [ManualInputFlag: appendix 2.93.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e22225) */
export declare const enum ManualInputFlag {
  NoEntry = 'NoEntry',
  ManualEntries = 'ManualEntries'
}

/** [ManufacturerCode: appendix 2.94.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e22253) */
export interface ManufacturerCode {
  value: string
}

/** [ManufacturerSpecificEventFaultData: appendix 2.95.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e22276) */
export interface ManufacturerSpecificEventFaultDataGen2 {
  manufacturerCode: ManufacturerCode
  manufacturerSpecificErrorCode: Array<number>
}

export interface MonthYear {
  month: number
  year: number
}

/** [Name: appendix 2.299.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e22398) */
export interface Name {
  codePage: number
  name: string
}

/** [NationNumeric: appendix 2.101.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e22450) */
export interface NationNumeric {
  value: string
}

/** [OdometerShort: appendix 2.113.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e22854) */
export interface OdometerShort {
  /** Value in km in the operating range 0 to 9 999 999 km. */
  km: number
}

export declare function parseCard(bytes: Buffer): CardData

export declare function parseTachoFile(bytes: Buffer): TachoData

export declare function parseVu(bytes: Buffer): VuData

/** [PlaceRecord: appendix 2.117.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e23112) */
export interface PlaceRecord {
  entryTime: TimeReal
  entryTypeDailyWorkPeriod: EntryTypeDailyWorkPeriod
  dailyWorkPeriodCountry: NationNumeric
  dailyWorkPeriodRegion: RegionNumeric
  vehicleOdometerValue: OdometerShort
}

/** [PlaceRecord: appendix 2.117.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e23112) */
export interface PlaceRecordGen2 {
  entryTime: TimeReal
  entryTypeDailyWorkPeriod: EntryTypeDailyWorkPeriodGen2
  dailyWorkPeriodCountry: NationNumeric
  dailyWorkPeriodRegion: RegionNumeric
  vehicleOdometerValue: OdometerShort
  entryGnssPlaceRecord: GnssPlaceRecordGen2
}

/** [PreviousVehicleInfo: appendix 2.118.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e23250) */
export interface PreviousVehicleInfo {
  vehicleRegistrationIdentification: VehicleRegistrationIdentification
  cardWithdrawalTime: TimeReal
}

/** [PreviousVehicleInfo: appendix 2.118.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e23250) */
export interface PreviousVehicleInfoGen2 {
  vehicleRegistrationIdentification: VehicleRegistrationIdentification
  cardWithdrawalTime?: TimeReal
  vuGeneration: GenerationGen2
}

/** [RecordType: appendix 2.120.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e23342) */
export declare const enum RecordTypeGen2 {
  ActivityChangeInfo = 'ActivityChangeInfo',
  CardSlotsStatus = 'CardSlotsStatus',
  CurrentDateTime = 'CurrentDateTime',
  MemberStateCertificate = 'MemberStateCertificate',
  OdometerValueMidnight = 'OdometerValueMidnight',
  DateOfDayDownloaded = 'DateOfDayDownloaded',
  SensorPaired = 'SensorPaired',
  Signature = 'Signature',
  SpecificConditionRecord = 'SpecificConditionRecord',
  VehicleIdentificationNumber = 'VehicleIdentificationNumber',
  VehicleRegistrationNumber = 'VehicleRegistrationNumber',
  VuCalibrationRecord = 'VuCalibrationRecord',
  VuCardIwRecord = 'VuCardIwRecord',
  VuCardRecord = 'VuCardRecord',
  VuCertificate = 'VuCertificate',
  VuCompanyLocksRecord = 'VuCompanyLocksRecord',
  VuControlActivityRecord = 'VuControlActivityRecord',
  VuDetailedSpeedBlock = 'VuDetailedSpeedBlock',
  VuDownloadablePeriod = 'VuDownloadablePeriod',
  VuDownloadActivityData = 'VuDownloadActivityData',
  VuEventRecord = 'VuEventRecord',
  VuGNSSADRecord = 'VuGNSSADRecord',
  VuITSConsentRecord = 'VuITSConsentRecord',
  VuFaultRecord = 'VuFaultRecord',
  VuIdentification = 'VuIdentification',
  VuOverSpeedingControlData = 'VuOverSpeedingControlData',
  VuOverSpeedingEventRecord = 'VuOverSpeedingEventRecord',
  VuPlaceDailyWorkPeriodRecord = 'VuPlaceDailyWorkPeriodRecord',
  VuTimeAdjustmentGNSSRecord = 'VuTimeAdjustmentGNSSRecord',
  VuTimeAdjustmentRecord = 'VuTimeAdjustmentRecord',
  VuPowerSupplyInterruptionRecord = 'VuPowerSupplyInterruptionRecord',
  SensorPairedRecord = 'SensorPairedRecord',
  SensorExternalGNSSCoupledRecord = 'SensorExternalGNSSCoupledRecord',
  RFU = 'RFU',
  ManufacturerSpecific = 'ManufacturerSpecific'
}

/** [RegionNumeric: appendix 2.122.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e23612) */
export interface RegionNumeric {
  value: string
}

/** [SealDataVu: appendix 2.129.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e23827) */
export interface SealDataVuGen2 {
  sealRecords: Array<SealRecordGen2>
}

/** [SealRecord: appendix 2.130.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e23854) */
export interface SealRecordGen2 {
  equipmentType: EquipmentTypeGen2
  extendedSealIdentifier: ExtendedSealIdentifierGen2
}

/** [SensorApprovalNumber: appendix 2.131.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e23887) */
export interface SensorApprovalNumber {
  value: string
}

/** [SensorApprovalNumber: appendix 2.131.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e23887) */
export interface SensorApprovalNumberGen2 {
  value: string
}

/** [SensorExternalGNSSApprovalNumber: appendix 2.132.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e23931) */
export interface SensorExternalGnssApprovalNumberGen2 {
  value: string
}

export interface SensorExternalGnssCoupledRecordGen2 {
  sensorSerialNumber: SensorGnssSerialNumberGen2
  sensorApprovalNumber: SensorExternalGnssApprovalNumberGen2
  sensorCouplingDate: SensorGnssCouplingDateGen2
}

/** [SensorPaired: appendix 2.144.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24360) */
export interface SensorPaired {
  sensorSerialNumber: SensorSerialNumber
  sensorApprovalNumber: SensorApprovalNumber
  sensorPairingDateFirst: SensorPairingDate
}

export interface SensorPairedRecordGen2 {
  sensorSerialNumber: SensorSerialNumberGen2
  sensorApprovalNumber: SensorApprovalNumberGen2
  sensorPairingDate: SensorPairingDate
}

/** [Signature: appendix 2.149.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24501) */
export interface Signature {
  value: Array<number>
}

/** [Signature: appendix 2.149.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24501) */
export interface SignatureGen2 {
  value: Array<number>
}

/** [SimilarEventsNumber: appendix 2.151.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24591) */
export interface SimilarEventsNumber {
  value: number
}

/** [SpecificConditionRecord: appendix 2.152.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24614) */
export interface SpecificConditionRecord {
  entryTime: TimeReal
  specificConditionType: SpecificConditionType
}

/** [SpecificConditionRecord: appendix 2.152.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24614) */
export interface SpecificConditionRecordGen2 {
  entryTime: TimeReal
  specificConditionType: SpecificConditionTypeGen2
}

/** [SpecificConditions: appendix 2.153.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24644) */
export interface SpecificConditions {
  specificConditionRecords: Array<SpecificConditionRecord>
}

/** [SpecificConditions: appendix 2.153.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24644) */
export interface SpecificConditionsGen2 {
  conditionPointerNewestRecord: NoOfSpecificConditionRecordsGen2
  specificConditionRecords: Array<SpecificConditionRecordGen2>
}

/** [SpecificConditionType: appendix 2.154.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24685) */
export declare const enum SpecificConditionType {
  RFU = 'RFU',
  OutOfScopeBegin = 'OutOfScopeBegin',
  OutOfScopeEnd = 'OutOfScopeEnd',
  FerryTrainCrossingBegin = 'FerryTrainCrossingBegin'
}

/** [SpecificConditionType: appendix 2.154.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24685) */
export declare const enum SpecificConditionTypeGen2 {
  RFU = 'RFU',
  OutOfScopeBegin = 'OutOfScopeBegin',
  OutOfScopeEnd = 'OutOfScopeEnd',
  FerryTrainCrossingBegin = 'FerryTrainCrossingBegin',
  FerryTrainCrossingEnd = 'FerryTrainCrossingEnd'
}

/** [Speed: appendix 2.155.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24822) */
export interface Speed {
  value: number
}

export type TachoData =
  | { type: 'Card', cardData: CardData }
  | { type: 'Vu', vuData: VuData }

export declare const enum TachoFileType {
  VehicleUnitGen1 = 'VehicleUnitGen1',
  VehicleUnitGen2 = 'VehicleUnitGen2',
  VehicleUnitGen2V2 = 'VehicleUnitGen2V2',
  DriverCardGen1 = 'DriverCardGen1',
  DriverCardGen2 = 'DriverCardGen2',
  DriverCardGen2V2 = 'DriverCardGen2V2'
}

/** [TimeReal: appendix 2.162.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24993) */
export interface TimeReal {
  value: Date
}

/** [TyreSize: appendix 2.163.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e25026) */
export interface TyreSize {
  value: string
}

/** [VehicleIdentificationNumber: appendix 2.165.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e25052) */
export interface VehicleIdentificationNumber {
  value: string
}

/** [VehicleRegistrationIdentification: appendix 2.116.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e25120) */
export interface VehicleRegistrationIdentification {
  vehicleRegistrationNation: NationNumeric
  vehicleRegistrationNumber: VehicleRegistrationNumber
}

/** [VehicleRegistrationNumber: appendix 2.168.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e25188) */
export interface VehicleRegistrationNumber {
  codePage: number
  vehicleRegNumber: string
}

/** [VuAbility: appendix 2.169.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e25277) */
export declare const enum VuAbilityGen2 {
  SupportsGen1 = 'SupportsGen1',
  SupportsGen2 = 'SupportsGen2',
  RFU = 'RFU'
}

/** Page 344 TREP 02 */
export interface VuActivitiesBlock {
  timeReal: TimeReal
  odometerValueMidnight: OdometerValueMidnight
  vuCardIwData: VuCardIwData
  vuActivityDailyData: VuActivityDailyData
  vuPlaceDailyWorkPeriodData: VuPlaceDailyWorkPeriodData
  vuSpecificConditionData: VuSpecificConditionData
  signature: Signature
}

export interface VuActivitiesBlockGen2 {
  dateOfDayDownloadedRecordArray: Array<DateOfDayDownloadedGen2>
  odometerValueMidnightRecordArray: Array<OdometerValueMidnight>
  vuCardIwRecordArray: Array<VuCardIwRecordGen2>
  vuActivityDailyRecordArray: Array<ActivityChangeInfo>
  vuPlaceDailyWorkPeriodRecordArray: Array<VuPlaceDailyWorkPeriodGen2>
  vuGnssAdRecordArray: Array<VuGnssadRecordGen2>
  vuSpecificConditionRecordArray: Array<SpecificConditionRecordGen2>
  signatureRecordArray: Array<SignatureGen2>
}

/** [VuActivityDailyData: appendix 2.170.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e25344) */
export interface VuActivityDailyData {
  noOfActivityChanges: number
  activityChangeInfos: Array<ActivityChangeInfo>
}

/** [VuApprovalNumber: appendix 2.172.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e25427) */
export interface VuApprovalNumber {
  value: string
}

/** [VuApprovalNumber: appendix 2.172.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e25427) */
export interface VuApprovalNumberGen2 {
  value: string
}

/** [VuCalibrationData: appendix 2.173.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e25471) */
export interface VuCalibrationData {
  noOfVuCalibrationRecords: number
  vuCalibrationRecords: Array<VuCalibrationRecord>
}

/** [VuCalibrationRecord: appendix 2.174.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e25500) */
export interface VuCalibrationRecord {
  calibrationPurpose: CalibrationPurpose
  workshopName: Name
  workshopAddress: Address
  workshopCardNumber: FullCardNumber
  workshopCardExpiryDate?: TimeReal
  vehicleIdentificationNumber?: VehicleIdentificationNumber
  vehicleRegistrationIdentification?: VehicleRegistrationIdentification
  wVehicleCharacteristicConstant: WVehicleCharacteristicConstant
  kConstantOfRecordingEquipment: KConstantOfRecordingEquipment
  lTyreCircumference: LTyreCircumference
  tyreSize: TyreSize
  authorisedSpeed: SpeedAuthorised
  oldOdometerValue: OdometerShort
  newOdometerValue: OdometerShort
  oldTimeValue?: TimeReal
  newTimeValue?: TimeReal
  nextCalibrationDate?: TimeReal
}

export interface VuCalibrationRecordGen2 {
  calibrationPurpose: CalibrationPurposeGen2
  workshopName: Name
  workshopAddress: Address
  workshopCardNumber: FullCardNumberGen2
  workshopCardExpiryDate?: TimeReal
  vehicleIdentificationNumber?: VehicleIdentificationNumber
  vehicleRegistrationIdentification?: VehicleRegistrationIdentification
  wVehicleCharacteristicConstant: WVehicleCharacteristicConstant
  kConstantOfRecordingEquipment: KConstantOfRecordingEquipment
  lTyreCircumference: LTyreCircumference
  tyreSize: TyreSize
  authorisedSpeed: SpeedAuthorised
  oldOdometerValue: OdometerShort
  newOdometerValue: OdometerShort
  oldTimeValue?: TimeReal
  newTimeValue?: TimeReal
  nextCalibrationDate?: TimeReal
  sealDataVu: SealDataVuGen2
}

export interface VuCardIwData {
  noOfIwRecords: number
  vuCardIwRecords: Array<VuCardIwRecord>
}

/** [VuCardIwRecord: appendix 2.177.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e25809) */
export interface VuCardIwRecord {
  cardHolderName: HolderName
  fullCardNumber: FullCardNumber
  cardExpiryDate: TimeReal
  cardInsertionTime: TimeReal
  vehicleOdometerValueAtInsertion: OdometerShort
  cardSlotNumber: CardSlotNumber
  cardWithdrawalTime?: TimeReal
  vehicleOdometerValueAtWithdrawal: OdometerShort
  previousVehicleInfo: PreviousVehicleInfo
  manualEntryFlag: ManualInputFlag
}

export interface VuCardIwRecordGen2 {
  cardHolderName: HolderName
  fullCardNumberAndGeneration: FullCardNumberAndGenerationGen2
  cardExpiryDate: TimeReal
  cardInsertionDate: TimeReal
  vehicleOdometerValueAtInsertion: OdometerShort
  cardSlotNumber: CardSlotNumber
  cardWithdrawlTime?: TimeReal
  vehicleOdometerValueAtWithdrawal: OdometerShort
  previousVehicleInfo: PreviousVehicleInfoGen2
  manualInputFlag: ManualInputFlag
}

export interface VuCardRecordGen2 {
  cardNumberAndGenerationInformation?: FullCardNumberAndGenerationGen2
  cardExtendedSerialNumber: ExtendedSerialNumberGen2
  cardStructureVersion: CardStructureVersion
  cardNumber?: CardNumber
}

/** [VuCompanyLocksBlock: appendix 2.236.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e28868) */
export interface VuCompanyLocksBlock {
  vuIdentification: VuIdentification
  sensorPaired: SensorPaired
  vuCalibrationData: VuCalibrationData
  signature: Signature
}

export interface VuCompanyLocksBlockGen2 {
  vuIdentificationRecordArray: Array<VuIdentificationGen2>
  vuSensorPairedRecordArray: Array<SensorPairedRecordGen2>
  vuSensorExternalGnssCoupledRecordArray: Array<SensorExternalGnssCoupledRecordGen2>
  vuCalibrationRecordArray: Array<VuCalibrationRecordGen2>
  vuCardRecordArray: Array<VuCardRecordGen2>
  vuItsConsentRecordArray: Array<VuItsConsentRecordGen2>
  vuPowerSupplyInterruptionRecordArray: Array<VuPowerSupplyInterruptionRecordGen2>
  signatureRecordArray: Array<SignatureGen2>
}

/** [VuCompanyLocksData: appendix 2.183.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e26258) */
export interface VuCompanyLocksData {
  noOfLocks: number
  vuCompanyLocksRecords: Array<VuCompanyLocksRecord>
}

export interface VuCompanyLocksGen2 {
  lockInTime: TimeReal
  lockOutTime?: TimeReal
  companyName: Name
  companyAddress: Address
  companyCardNumberAndGeneration: FullCardNumberAndGenerationGen2
}

/** [VuCompanyLocksRecord: appendix 2.184.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e26153) */
export interface VuCompanyLocksRecord {
  lockInTime: TimeReal
  lockOutTime?: TimeReal
  companyName: Name
  companyAddress: Address
  companyCardNumber: FullCardNumber
}

/** [VuControlActivityData: appendix 2.186.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e26342) */
export interface VuControlActivityData {
  noOfControls: number
  vuControlActivityRecords: Array<VuControlActivityRecord>
}

export interface VuControlActivityGen2 {
  controlType: ControlTypeGen2
  controlTime: TimeReal
  controlCardNumberAndGeneration: FullCardNumberAndGenerationGen2
  downloadPeriodBeginTime: TimeReal
  downloadPeriodEndTime: TimeReal
}

/** [VuControlActivityRecord: appendix 2.187.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e26392) */
export interface VuControlActivityRecord {
  controlType: ControlType
  controlTime: TimeReal
  controlCardNumber: FullCardNumber
  downloadPeriodBeginTime: TimeReal
  downloadPeriodEndTime: TimeReal
}

export type VuData =
  | { type: 'VuGen1Blocks', data: VuGen1Blocks }
  | { type: 'VuGen2Blocks', data: VuGen2Blocks }
  | { type: 'VuGen2V2Blocks', data: VuGen2V2Blocks }

/** [VuDataBlockCounter: appendix 2.189.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e26512) */
export interface VuDataBlockCounter {
  value: number
}

/** [VuDetailedSpeedBlock: appendix 2.224.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e26534) */
export interface VuDetailedSpeedBlock {
  speedBlockBeginDate: TimeReal
  speedsPerSecond: Array<Speed>
}

/** [VuDetailedSpeedData: appendix 2.192.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e26618) */
export interface VuDetailedSpeedData {
  noOfSpeedBlocks: number
  vuDetailedSpeedRecords: Array<VuDetailedSpeedBlock>
}

/** [VuDownloadablePeriod: appendix 2.193](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e26674) */
export interface VuDownloadablePeriod {
  minDownloadableTime: TimeReal
  maxDownloadableTime: TimeReal
}

/** [VuDownloadActivityData: appendix 2.195.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e26758) */
export interface VuDownloadActivityData {
  downloadingTime: TimeReal
  fullCardNumber: FullCardNumber
  companyOrWorkshopName: Name
}

export interface VuDownloadActivityDataGen2 {
  downloadingTime?: TimeReal
  fullCardNumberAndGeneration?: FullCardNumberAndGenerationGen2
  companyOrWorkshopName?: Name
}

/** [VuEventData: appendix 2.197.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e26876) */
export interface VuEventData {
  noOfVuEventRecords: number
  vuEventRecords: Array<VuEventRecord>
}

/** [VuEventRecord: appendix 2.197.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e26910) */
export interface VuEventRecord {
  eventType: EventFaultType
  eventRecordPurpose: EventFaultRecordPurpose
  eventBeginTime: TimeReal
  eventEndTime?: TimeReal
  cardNumberDriverSlotBegin?: FullCardNumber
  cardNumberCodriverSlotBegin?: FullCardNumber
  cardNumberDriverSlotEnd?: FullCardNumber
  cardNumberCodriverSlotEnd?: FullCardNumber
  similarEventsNumber: SimilarEventsNumber
}

export interface VuEventRecordGen2 {
  eventType: EventFaultTypeGen2
  eventRecordPurpose: EventFaultRecordPurpose
  eventBeginTime: TimeReal
  eventEndTime?: TimeReal
  cardNumberAndGenDriverSlotBegin?: FullCardNumberAndGenerationGen2
  cardNumberAndGenCodriverSlotBegin?: FullCardNumberAndGenerationGen2
  cardNumberAndGenDriverSlotEnd?: FullCardNumberAndGenerationGen2
  cardNumberAndGenCodriverSlotEnd?: FullCardNumberAndGenerationGen2
  similarEventsNumber: SimilarEventsNumber
  manufacturerSpecificEventFaultData?: ManufacturerSpecificEventFaultDataGen2
}

/** TREP 03 page 346 */
export interface VuEventsAndFaultsBlock {
  vuFaultData: VuFaultData
  vuEventData: VuEventData
  vuOverSpeedingControlData: VuOverSpeedingControlData
  vuOverSpeedingEventData: VuOverSpeedingEventData
  vuTimeAdjustmentData: VuTimeAdjustmentData
  signature: Signature
}

export interface VuEventsAndFaultsBlockGen2 {
  vuFaultRecordArray: Array<VuFaultRecordGen2>
  vuEventRecordArray: Array<VuEventRecordGen2>
  vuOverSpeedingControlDataRecordArray: Array<VuOverSpeedingControlDataGen2>
  vuOverSpeedingEventRecordArray: Array<VuOverSpeedingEventRecordGen2>
  vuTimeAdjustmentRecordArray: Array<VuTimeAdjustmentRecordGen2>
  signatureRecordArray: Array<SignatureGen2>
}

/** [VuFaultRecord: appendix 2.200.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e27122) */
export interface VuFaultData {
  noOfVuFaultRecords: number
  vuFaultRecords: Array<VuFaultRecord>
}

/** [VuFaultRecord: appendix 2.201.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e27156) */
export interface VuFaultRecord {
  faultType: EventFaultType
  faultRecordPurpose: EventFaultRecordPurpose
  faultBeginTime: TimeReal
  faultEndTime: TimeReal
  cardNumberDriverSlotBegin?: FullCardNumber
  cardNumberCodriverSlotBegin?: FullCardNumber
  cardNumberDriverSlotEnd?: FullCardNumber
  cardNumberCodriverSlotEnd?: FullCardNumber
}

export interface VuFaultRecordGen2 {
  faultType: EventFaultTypeGen2
  faultRecordPurpose: EventFaultRecordPurpose
  faultBeginTime: TimeReal
  faultEndTime: TimeReal
  cardNumberAndGenDriverSlotBegin?: FullCardNumberAndGenerationGen2
  cardNumberAndGenCodriverSlotBegin?: FullCardNumberAndGenerationGen2
  cardNumberAndGenDriverSlotEnd?: FullCardNumberAndGenerationGen2
  cardNumberAndGenCodriverSlotEnd?: FullCardNumberAndGenerationGen2
  manufacturerSpecificEventFaultData?: ManufacturerSpecificEventFaultDataGen2
}

export interface VuGen1Blocks {
  vuOverview: VuOverviewBlock
  vuActivities: Array<VuActivitiesBlock>
  vuEventsAndFaults: Array<VuEventsAndFaultsBlock>
  vuDetailedSpeed: Array<VuDetailedSpeedData>
  vuCompanyLocks: Array<VuCompanyLocksBlock>
}

export interface VuGen2Blocks {
  vuOverview: VuOverviewBlockGen2
  vuActivities: Array<VuActivitiesBlockGen2>
  vuEventsAndFaults: Array<VuEventsAndFaultsBlockGen2>
  vuDetailedSpeed: Array<VuSpeedBlockGen2>
  vuCompanyLocks: Array<VuCompanyLocksBlockGen2>
}

export interface VuGen2V2Blocks {
  vuOverview: VuOverviewBlock
}

/** [VuGNSSADRecord: appendix 2.203.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e27345) */
export interface VuGnssadRecordGen2 {
  timeStamp: TimeReal
  cardNumberAndGenDriverSlot?: FullCardNumberAndGenerationGen2
  cardNumberAndGenCodriverSlot?: FullCardNumberAndGenerationGen2
  gnssPlaceRecord: GnssPlaceRecordGen2
  vehicleOdometerValue: OdometerShort
}

export interface VuIdentification {
  vuManufacturerName: VuManufacturerName
  vuManufacturerAddress: VuManufacturerAddress
  vuPartNumber: VuPartNumber
  vuSerialNumber: VuSerialNumber
  vuSoftwareIdentification: VuSoftwareIdentification
  vuManufacturingDate: VuManufacturingDate
  vuApprovalNumber: VuApprovalNumber
}

export interface VuIdentificationGen2 {
  vuManufacturerName: VuManufacturerName
  vuManufacturerAddress: VuManufacturerAddress
  vuPartNumber: VuPartNumber
  vuSerialNumber: VuSerialNumberGen2
  vuSoftwareIdentification: VuSoftwareIdentification
  vuManufacturingDate: VuManufacturingDate
  vuApprovalNumber: VuApprovalNumberGen2
  vuGeneration: GenerationGen2
  vuAbility: VuAbilityGen2
}

export interface VuItsConsentRecordGen2 {
  cardNumberAndGen?: FullCardNumberAndGenerationGen2
  consent: boolean
}

/** [VuOverSpeedingControlData: appendix 2.212.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e27978) */
export interface VuOverSpeedingControlData {
  lastOverspeedControlTime?: TimeReal
  firstOverspeedSince?: TimeReal
  numberOfOverspeedSince: OverspeedNumber
}

export interface VuOverSpeedingControlDataGen2 {
  lastOverspeedControlTime?: TimeReal
  firstOverspeedSince?: TimeReal
  numberOfOverspeedSince?: OverspeedNumber
}

/** [VuOverSpeedingEventData: appendix 2.214.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e28064) */
export interface VuOverSpeedingEventData {
  noOfVuOverSpeedingEvents: number
  vuOverSpeedingEventRecords: Array<VuOverSpeedingEventRecord>
}

/** [VuOverSpeedingEventRecord: appendix 2.215.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e28097) */
export interface VuOverSpeedingEventRecord {
  eventType: EventFaultType
  eventRecordPurpose: EventFaultRecordPurpose
  eventBeginTime: TimeReal
  eventEndTime: TimeReal
  maxSpeedValue: SpeedMax
  averageSpeedValue: SpeedAverage
  cardNumberDriverSlot: FullCardNumber
  similarEventsNumber: SimilarEventsNumber
}

export interface VuOverSpeedingEventRecordGen2 {
  eventType: EventFaultTypeGen2
  eventRecordPurpose: EventFaultRecordPurpose
  eventBeginTime: TimeReal
  eventEndTime: TimeReal
  maxSpeedValue: SpeedMax
  averageSpeedValue: SpeedAverage
  cardNumberAndGenDriverSlotBegin?: FullCardNumberAndGenerationGen2
  similarEventsNumber: SimilarEventsNumber
}

/** [VuOverviewBlock page 342] */
export interface VuOverviewBlock {
  memberStateCertificate: Certificate
  vuCertificate: Certificate
  vehicleIdentificationNumber: VehicleIdentificationNumber
  vehicleRegistrationIdentification: VehicleRegistrationIdentification
  currentDateTime: TimeReal
  vuDownloadablePeriod: VuDownloadablePeriod
  cardSlotsStatus: CardSlotsStatus
  vuDownloadActivityData: VuDownloadActivityData
  vuCompanyLocksData: VuCompanyLocksData
  vuControlActivityData: VuControlActivityData
  signature: Signature
}

export interface VuOverviewBlock {
  memberStateCertificateRecordArray: Array<MemberStateCertificateGen2>
  vuCertificateRecordArray: Array<VuCertificateGen2>
  vehicleIdentificationNumberRecordArray: Array<VehicleIdentificationNumber>
  vehicleRegistrationNumberRecordArray: Array<VehicleRegistrationNumber>
}

export interface VuOverviewBlockGen2 {
  memberStateCertificateRecordArray: Array<MemberStateCertificateGen2>
  vuCertificateRecordArray: Array<VuCertificateGen2>
  vehicleIdentificationNumberRecordArray: Array<VehicleIdentificationNumber>
  vehicleRegistrationNumberRecordArray: Array<VehicleRegistrationNumber>
  currentDateTimeRecordArray: Array<CurrentDateTime>
  vuDownloadablePeriodRecordArray: Array<VuDownloadablePeriod>
  cardSlotsStatusRecordArray: Array<CardSlotsStatus>
  vuDownloadActivityDataRecordArray: Array<VuDownloadActivityDataGen2>
  vuCompanyLocksRecordArray: Array<VuCompanyLocksGen2>
  vuControlActivityRecordArray: Array<VuControlActivityGen2>
  signatureRecordArray: Array<SignatureGen2>
}

/** [VuPartNumber: appendix 2.217.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e28257) */
export interface VuPartNumber {
  value: string
}

/** [VuPlaceDailyWorkPeriodData: appendix 2.218.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e28280) */
export interface VuPlaceDailyWorkPeriodData {
  noOfPlaceRecords: number
  vuPlaceDailyWorkPeriodRecords: Array<VuPlaceDailyWorkPeriodRecord>
}

export interface VuPlaceDailyWorkPeriodGen2 {
  fullCardNumberAndGeneration?: FullCardNumberAndGenerationGen2
  placeRecord: PlaceRecordGen2
}

/** [VuPlaceDailyWorkPeriodRecord: appendix 2.219.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e28313) */
export interface VuPlaceDailyWorkPeriodRecord {
  fullCardNumber: FullCardNumber
  placeRecord: PlaceRecord
}

export interface VuPowerSupplyInterruptionRecordGen2 {
  eventType: EventFaultTypeGen2
  eventRecordPurpose: EventFaultRecordPurpose
  eventBeginTime: TimeReal
  eventEndTime: TimeReal
  cardNumberAndGenDriverSlotBegin?: FullCardNumberAndGenerationGen2
  cardNumberAndGenDriverSlotEnd?: FullCardNumberAndGenerationGen2
  cardNumberAndGenCodriverSlotBegin?: FullCardNumberAndGenerationGen2
  cardNumberAndGenCodriverSlotEnd?: FullCardNumberAndGenerationGen2
  similarEventsNumber: SimilarEventsNumber
}

/** [VuSoftwareIdentification: appendix 2.225.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e28538) */
export interface VuSoftwareIdentification {
  vuSoftwareVersion: VuSoftwareVersion
  vuSoftInstallationDate: VuSoftInstallationDate
}

/** [VuSoftwareVersion: appendix 2.226.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e28569) */
export interface VuSoftwareVersion {
  value: string
}

/** [VuSpecificConditionData: appendix 2.227.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e28591) */
export interface VuSpecificConditionData {
  noOfSpecificConditions: number
  specificConditionRecords: Array<SpecificConditionRecord>
}

/** [VuSpecificConditionRecord: appendix 2.152.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24614) */
export interface VuSpecificConditionRecord {
  entryTime: TimeReal
  specificConditionType: SpecificConditionType
}

export interface VuSpeedBlockGen2 {
  vuDetailedSpeedBlockRecordArray: Array<VuDetailedSpeedBlock>
  signatureRecordArray: Array<SignatureGen2>
}

/** [VuTimeAdjustmentData: appendix 2.229.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e28675) */
export interface VuTimeAdjustmentData {
  noOfVuTimeAdjRecords: number
  vuTimeAdjustmentRecords: Array<VuTimeAdjustmentRecord>
}

/** [VuTimeAdjustmentRecord: appendix 2.232.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e28728) */
export interface VuTimeAdjustmentRecord {
  oldTimeValue: Date
  newTimeValue: Date
  workshopName: Name
  workshopAddress: Address
  workshopCardNumber: FullCardNumber
}

/** [VuTimeAdjustmentRecord: appendix 2.232.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e28728)  */
export interface VuTimeAdjustmentRecordGen2 {
  oldTimeValue: Date
  newTimeValue: Date
  workshopName: Name
  workshopAddress: Address
  workshopCardNumberAndGeneration?: FullCardNumberAndGenerationGen2
}

/** [WVehicleCharacteristicConstant: appendix 2.239.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e29395) */
export interface WVehicleCharacteristicConstant {
  value: number
}


// Post processed types from src/post-process.ts 

export type SensorSerialNumber = ExtendedSerialNumber;

/** [NoOfCardPlaceRecords: appendix 2.104.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e22566) */
export type NoOfCardPlaceRecords = number;

/** [VuSerialNumber: appendix 2.223.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e28497) */
export type VuSerialNumber = ExtendedSerialNumber;

/** [MemberStateCertificate: appendix 2.96.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e22309) */
export type MemberStateCertificateGen2 = CertificateGen2;

/** [VuCertificate: appendix 2.181.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e26086) */
export type VuCertificateGen2 = CertificateGen2;

/** [VuSerialNumber: appendix 2.223.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e28497) */
export type VuSerialNumberGen2 = ExtendedSerialNumberGen2;

/** [SensorSerialNumber: appendix 2.148.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24483) */
export type SensorSerialNumberGen2 = ExtendedSerialNumberGen2;

/** [SensorGNSSSerialNumber: appendix 2.139.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24175) */
export type SensorGnssSerialNumberGen2 = ExtendedSerialNumberGen2;

export type SensorGnssCouplingDateGen2 = TimeReal;

/** [NoOfEventsPerType: appendix 2.109.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e22706) */
export type NoOfEventsPerTypeGen2 = number;

/** [NoOfFaultsPerType: appendix 2.110.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e22729) */
export type NoOfFaultsPerTypeGen2 = number;

/** [NoOfCardVehicleRecords: appendix 2.105.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e22612) */
export type NoOfCardVehicleRecordsGen2 = number;

/** [NoOfCardPlaceRecords: appendix 2.104.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e22566) */
export type NoOfCardPlaceRecordsGen2 = number;

/** [NoOfGnssAdRecords: appendix 2.111.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e22756) */
export type NoOfGnssAdRecordsGen2 = number;

/** [NoOfSpecificConditionRecords: appendix 2.112.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e22807) */
export type NoOfSpecificConditionRecordsGen2 = number;

/** [NoOfCardVehicleUnitRecords: appendix 2.106.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e22635) */
export type NoOfCardVehicleUnitRecordsGen2 = number;

/** [SpeedAuthorised: appendix 2.156.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24843) */
export type SpeedAuthorised = Speed;

/** [SpeedAverage: appendix 2.157.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24860) */
export type SpeedAverage = Speed;

/** [SpeedMax: appendix 2.158.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24877) */
export type SpeedMax = Speed;

/** [OverspeedNumber: appendix 2.116.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e23023) */
export type OverspeedNumber = Speed;

/** [VuManufacturerName: appendix 2.240.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e25160) */
export type VuManufacturerName = Name;

/** [VuManufacturerAddress: appendix 2.209.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e27911) */
export type VuManufacturerAddress = Address;

/** [VuSoftInstallationDate: appendix 2.224.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e28515) */
export type VuSoftInstallationDate = TimeReal;

/** [VuManufacturingDate: appendix 2.211.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e27955) */
export type VuManufacturingDate = TimeReal;

/** [OdometerValueMidnight: appendix 2.114.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e22880) */
export type OdometerValueMidnight = OdometerShort;

/** [LastCardDownload: appendix 2.89.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e22044) */
export type LastCardDownload = TimeReal;

/** [CardActivityLengthRange: appendix 2.10.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e16777) */
export type CardActivityLengthRange = number;

/** [SensorPairingDate: appendix 2.146.](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R0799-20230821#cons_toc_d1e24438) */
export type SensorPairingDate = TimeReal;